### ISSUE TITLE
Emoticon filters interface

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#100]
Similar to the regular filters, but in that mode you enter URL to file or upload one as the Replacement. I'd just add "Emoticon" column in Chat Filters and a checkbox in each row.

**Comment by calzoneman** [comment]
So basically, an auto generator for `<img src="blah">`?  I'd rather avoid user uploads (I thought about this when doing the custom CSS and custom JS feature); it opens a pandora's box of issues to deal with.

I know it may seem like I'm questioning a lot of features recently; this is because we've gone through all the major useful features and getting down to minor things.  My goal with this project was to keep it simple, both from a code perspective and from a UX perspective.

**Comment by ghost** [comment]
I get it, the KISS approach.

**Comment by calzoneman** [comment]
I might just add a little notice "If you're just trying to make an emoticon, use the following settings: ..."
