### ISSUE TITLE
Playlist load/save, stored on the accout.

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#117]

**Comment by calzoneman** [comment]
This has been requested by almost everyone since I put up the site.  A while back I added the ability to queue a comma-separated list of links, and the get playlist urls button as a temporary solution.  I still haven't thought of a good way to integrate this with the UI without cluttering it up.  If you have ideas, please let me know.

The code behind it is the easy part, it's getting it to look nice that's difficult.

**Comment by calzoneman** [comment]
With password resets out of the way, this is the next big feature in the queue.  I'll begin work on it next week probably.
