### ISSUE TITLE
Visits - Uniques - Viewing

### ISSUE THREAD

**Issue by Attiasthehun** [calzoneman/sync#129]
Another nice thing Synchtube had was the "Visits, Uniques, Viewing"
Viewing we already have as 'Connected Users' 

What if that was moved and put under 'Viewing'
And a Visits and Uniques counter was made

Then copy and paste the Profile avatar code and add a "Room avatar" as well 
So we get something like this above the MOTD

http://screencap.net/f/b554764a.png
As a room owner its awesome to follow something like that.

**Comment by calzoneman** [comment]
If you want to put a profile image, you can use &lt;img&gt; tags in the MOTD.

As for the visits and uniques, maybe.  I mean I like numbers, but I often find myself collecting unnecessary amounts of useless data.  I can pretty accurately guess how popular channels are just by how many people are in it at various times of day.

Part of the reason I started this project is because I didn't like Synchtube- I felt it was overcomplicated and cluttered.

**Comment by Attiasthehun** [comment]
Oh i see, yes well you kinda covered everything that needs to be done, you've done an excellent job.
I just remembered how nice a counter was in rooms for room owners to also keep a track on it, 

the room avatar was mainly just to style the thing so its wasn't just numbers, but you can think about it 
to me it just sounded like a nice little extra feature to kick in there.
