### ISSUE TITLE
Error when loading synch room page

### ISSUE THREAD

**Issue by SirShiggyDiggy** [calzoneman/sync#132]
I was in a room when suddenly i got disconnected, i tried to refresh the page when this is all i got. 

![0khdzhx](https://f.cloud.github.com/assets/4455297/517009/86b21960-becd-11e2-96fe-e53606b51a1d.png)
I have tried joining other rooms with no success. I have also tried all the troubleshooting i could but could find no fix.

I know that one of my friends also has this problem. He used to be able to connect to the room as well, but now he cant. its quite Inconvenient because he is the leader of the room.

_UPDATE_
Mine has spontaneously started to work again.

My friend (the admin/creator of the room) has connected to the room on one of his school computers, but he has lost his admin status over the room.

**Comment by Attiasthehun** [comment]
Is your friend logged in, or is he connected as a Guest.

**Comment by calzoneman** [comment]
I suspect this may have been a browser cache issue.  When I update the software I often change the Javascript on the page.  Some browsers might continue to use cached versions (which are outdated) which could cause errors.

For future reference, it would really help if you open your Javascript console (Ctrl-Shift-J on Chrome, Ctrl-Shift-K on Firefox).  Otherwise I have no insight as to what could be the problem (the entire project is over 7000 lines of code, so there's literally hundreds of things that could break).

Try clearing your cache and reloading the page.

**Comment by NippleKing** [comment]
I'm the friend (admin/creator of the room) of SirShiggyDiggy; I'm still having trouble connecting.
The Javascript console gives me the following error message:
"Unable to post message to http://www.youtube.com. Recipient has origin http://cytu.be."

Now, this doesn't give me information on what exactly causes the problem, but maybe you get something out of this.

**Comment by calzoneman** [comment]
That error is normal, it's just because of cross-domain policy of the browser and it doesn't affect anything.

If you still can't connect after clearing your cache, try disabling all your extensions or using a different browser.  This can narrow down the cause of the problem.

I already know for a fact that the HTTPS Everywhere extension causes issues for people.

**Comment by NippleKing** [comment]
Safari seems to work.

**Comment by calzoneman** [comment]
Have you tried disabling extensions in other browsers?  The analytics for my site show that the vast majority of users are on Firefox or Chrome, so I'm tempted to believe you have an extension that interferes with websockets.

I would also try opening it in an incognito window or private browsing to see what happens with no cookies/cache.

EDIT: It might also be an issue with your connection.  I'm not sure if it's possible for network administrators to block websockets, but if the site HTML loads and the channel doesn't then something is disallowing the websocket connection (or your DNS lookup fails).  Pop into http://webchat.6irc.net/?channels=synchtube

**Comment by calzoneman** [comment]
Update: I think I figured out what is causing the problem, but I still have no idea why this is happening, especially only to a select few individuals.

Through a test server and a volunteer who had the same issue, I determined that running the server on port 80 triggers the problem.

**Comment by calzoneman** [comment]
@NippleKing do you have any firewall/antivirus software?  Researching the issue, and that might have to do with it.
