### ISSUE TITLE
Changing the native path

### ISSUE THREAD

**Issue by X-15** [calzoneman/sync#134]
Hi,

I have a bigger portal and using CyTube on a port like :1337 doesn't really work, so I was wondering if there is a way to make it work from for example, domain.com/synch/ 

I'm on Ubunutu 12.04 using a vServer.

Thanks in advance.

**Comment by calzoneman** [comment]
I'm not exactly clear on what you're trying to do, so I'll attempt to answer this as best I can:
- If something else is already listening on port 80, you can't bind to it, but...
- You can serve the HTML content from a webserver and run the websocket through another port (I used to do this) but...
- This requires some .htaccess trickery if you want the `/r/channelname` syntax (I used to do this on my server, but I switched to just using the built in webserver because I was tired of maintaining it).  I think I solved all the cross-domain issues.

EDIT: Also, you have to copy the socket.io client from somewhere in node_modules to the webserver, but I don't remember the exact path.

EDIT EDIT: Depending on your webserver, you might be able to do some vhost trickery to map traffic to port 80 on a certain subdomain to the CyTube server running on a different port (I know nginx can do this with some kind of tcp_proxy module).

**Comment by X-15** [comment]
Hi, I'm sorry if it wasn't clear enough.
I have a pretty big website, to make the cytube more userfriendly I'd like to have the script running in mydomain.com/forexamplesynch/  instead of mydomain.com:1337 (or any other port). 

I read your suggestions, but I'm pretty new to linux and all that stuff, so a deeper going explanation would be awesome. I'm pretty sure I'm not the only one who want to use the script this way.

Thanks

**Comment by calzoneman** [comment]
I can try to help you with this, it just might take a bit because I actually have to figure out the steps to doing it myself.

**Comment by X-15** [comment]
Ok, awesome, thanks

**Comment by calzoneman** [comment]
Ok, starting in a fresh installation of cytube:
- `cp -r www/ /path/to/web/dir`
- `cp -r node_modules/socket.io/node_modules/socket.io-client/dist /path/to/web/dir/socket.io`

Create the following `.htaccess` file in /path/to/web/dir (assumes you have mod_rewrite enabled for that directory):

```
Options +FollowSymlinks
RewriteEngine on
RewriteRule ^r/([a-zA-Z0-9]+)$ channel.html [NC]
RewriteRule ^r/(.*/)+(.*)$ $1/$2 [NC]
RewriteRule ^r/(.*)\.html $1.html [NC]
```

Please note that you still have to update `WEB_URL` with the built-in webserver details because many pages rely on the functions of the built in webserver.

**Comment by X-15** [comment]
Hi, 
you rock! On the first sight it works well! Gotta test it around, if I find bugs, I'll post here.

**Comment by X-15** [comment]
Hi again, unfort. there are several bugs. I followed your guide and ended up with following:

/synch/Index.html
Failed to load resource http://myip:1337/synch/socket.io/socket.io.js?_=1368997054455
Failed to load resource http://myip:8080/synch/api/json/listloaded?filter=public&callback=jQuery1910601461936486885_1368997054456&_=1368997054457
GET http://myip:8080/synch/api/json/listloaded?filter=public&callback=jQuery1910601461936486885_1368997054458&_=1368997054459  jquery.js:8336
send jquery.js:8336
jQuery.extend.ajax jquery.js:7978
jQuery.(anonymous function) jquery.js:7614
jQuery.extend.getJSON jquery.js:8108
refresh:46.38.233.220:130

/synch/r/somepage
Uncaught TypeError: Cannot call method 'emit' of undefined media.js:70
player.YT.Player.events.onReady media.js:70
R.v www-widgetapi-vfljOMFPq.js:12
m.g www-widgetapi-vfljOMFPq.js:21
m.A www-widgetapi-vfljOMFPq.js:24
X.d www-widgetapi-vfljOMFPq.js:23
Va.f www-widgetapi-vfljOMFPq.js:17
GET http://myip:1337/synch/socket.io/socket.io.js?_=1368997216971  
jquery.js:8336
send jquery.js:8336
jQuery.extend.ajax jquery.js:7978
jQuery.(anonymous function) jquery.js:7614
jQuery.extend.getScript jquery.js:8104
(anonymous function) iourl.js:15

Let me know if you wanna contact me privately.

**Comment by calzoneman** [comment]
The `IO_URL` and `WEB_URL` should not include the /synch/ because they refer to the built in server, which knows nothing about your Apache configuration.  The /synch/ is only your Apache path.

Everything behind the scenes should be configured as if it is standalone.  The steps I listed above are just a trick to mirroring the static files from Apache so that you can use a non-standard URL.

**Comment by X-15** [comment]
Ok, I applied the changes, now following:

/synch/index.html
GET http://myip:1337/socket.io/socket.io.js?_=1368999283845 jquery.js:8336
send jquery.js:8336
jQuery.extend.ajax jquery.js:7978
jQuery.(anonymous function) jquery.js:7614
jQuery.extend.getScript jquery.js:8104
(anonymous function) iourl.js:15

GET http://myip:8080/api/json/listloaded?filter=public&callback=jQuery191014900235226377845_1368999283846&_=1368999283847 jquery.js:8336
send jquery.js:8336
jQuery.extend.ajax jquery.js:7978
jQuery.(anonymous function) jquery.js:7614
jQuery.extend.getJSON jquery.js:8108
refresh myip:130
(anonymous function) myip:98

/synch/r/somepage
Uncaught TypeError: Cannot call method 'emit' of undefined media.js:70
player.YT.Player.events.onReady media.js:70
R.v www-widgetapi-vfljOMFPq.js:12
m.g www-widgetapi-vfljOMFPq.js:21
m.A www-widgetapi-vfljOMFPq.js:24
X.d www-widgetapi-vfljOMFPq.js:23
Va.f www-widgetapi-vfljOMFPq.js:17

GET http://myip:1337/socket.io/socket.io.js?_=1368999389812 jquery.js:8336
send jquery.js:8336
jQuery.extend.ajax jquery.js:7978
jQuery.(anonymous function) jquery.js:7614
jQuery.extend.getScript jquery.js:8104
(anonymous function) iourl.js:15

When trying to login as guest:
Uncaught TypeError: Cannot call method 'emit' of undefined client.js:211
guestLogin client.js:211
jQuery.event.dispatch jquery.js:3074
elemData.handle jquery.js:2750

Also another weird bug. When I'm at myip/synch/index.html and I enter some channel like myip/synch/r/somechannel and from this channel click on Home button it redirects me to myip/synch/r/index.html

**Comment by calzoneman** [comment]
Join http://webchat.6irc.net/?channels=synchtube
