### ISSUE TITLE
Anything can be added into MOTD including full javascript, and html of anykind.

### ISSUE THREAD

**Issue by Ren6767** [calzoneman/sync#140]
There is possible XSS exploits which can be very dangerous for outdated computers or even 0day exploits can be added into the MOTD. It would be great to limit it into BBCode like [img] [b][url] for these kind of things.

**Comment by calzoneman** [comment]
Did you actually test this before opening the issue?  I tested `<script>` tags in the MOTD on both Firefox and Chromium, and neither one processed the script because the MOTD is wrapped in a `<p>` tag.

Secondly, there is actually an option for channel owners to add custom Javascript to the page.  I know it's less secure to allow moderators to run JS as well, but as I stated above I can't actually reproduce the ability for non-owners to add JS to the page.

**Comment by Ren6767** [comment]
Put this into the MOTD

(`<img src="asdf" onerror="alert(document.cookie)"/>`)

**Comment by calzoneman** [comment]
GitHub's markup ate your code, put it in grave accents to treat it as code (``)

**Comment by Ren6767** [comment]
Thanks, I edited my comment so you can see it.

**Comment by calzoneman** [comment]
Hmm, I'll reopen this so that I can prevent moderators from using Javascript, but keep in mind that channel owners can add Javascript anyways.

**Comment by calzoneman** [comment]
With the permissions update, you can control whether or not moderators can edit the MOTD.  If you don't trust your moderators, you can set it to be only editable by channel admins (who can already edit the channel JS anyways).
