### ISSUE TITLE
no longer allows anyone to add videos

### ISSUE THREAD

**Issue by bloxhead** [calzoneman/sync#145]
my tube used to let anyone add videos and now it won't work at all. any ideas?

**Comment by calzoneman** [comment]
If you're on synchtube.6irc.net (I haven't rolled out the latest update to cytu.be yet), I applied an update which replaces the old "allow anyone to do foo" checkboxes with a proper permissions system.  By default it only allows non-moderators to add videos if the queue is unlocked (big red button under the playlist).

You can fine tune the settings in the Channel Permissions tab (channel administrators can see this); Open queue permissions applies to when the queue is unlocked, general queue otherwise.

I'm afraid I can't help any more without knowing the channel and host you're on.

**Comment by bloxhead** [comment]
I'm actually on TaimaTube on 420chan.  Does that change anything?

**Comment by calzoneman** [comment]
I have no idea what version of the software they're using, you'll have to ask their administrator if you're having problems.
