### ISSUE TITLE
Fix media option/button

### ISSUE THREAD

**Issue by Zalg0** [calzoneman/sync#189]
Wondering if it would be possible to add a "fix media" button like the one that was on synchtube. All this button would do is refresh/reload the video that was currently playing if there was an issue with the video instead of having to refresh the entire page.

**Comment by awused** [comment]
I'll second this. There's a particular bug with youtube where it decides that the current time is the end of the video. This results in the player looping the "last" couple of seconds of the truncated video.

**Comment by calzoneman** [comment]
I should see if there's an open bug report on YouTube for that, and if not I'll submit it.

**Comment by awused** [comment]
I believe it's related to their changes to buffering that, well, stops buffering the video past a few seconds into the future. I guess it's to save bandwidth but it's resulted in a lot of usability issues. Combine it with the annoying tendency to think you'd rather have an unwatchable 144p smudge instead of waiting for your 720p video to buffer and you can't help but think the youtube devs are malicious.

**Comment by calzoneman** [comment]
Yeah, that's why I added the quality selector, so you can force it not to assume you're watching on a toaster.
