### ISSUE TITLE
Fall Back to Next Best Resolution

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#196]
If the user has a resolution selected that the video doesn't support the player should default to the next best resolution (ie, 1080p selected but only 720p is available -> use 720p).

You might already be doing this in some cases but I know selecting 720p _while_ a video with only 480p available is playing won't select 480p on the current video, at least.

**Comment by calzoneman** [comment]
It actually doesn't change the quality mid-video I think.  I can't remember if I fixed that or not.

However, this is already the behaviour of YouTube's JS API.  I send them a "suggested quality" and it picks the best one it can that is at most the quality I pass (so passing "720p" to a video which only has 480 would pick 480)

**Comment by calzoneman** [comment]
So I actually had fixed it to where it would change quality as soon as you select a different one, ~~but it turns out the function name in their documentation doesn't actually match the one that the player exposes.  I'll fix it.~~ The function name is actually correct, I'm guessing it's just their player being dumb.

On a side node, YouTube is being dumber and dumber these days.  I think even if you manually switch the quality, it still plays the buffered video at the current quality and only unbuffered parts of the video will be loaded in higher quality (in my experience).

**Comment by awused** [comment]
If I'm not wrong it'll also conveniently "forget" to upgrade the quality sometimes.

**Comment by calzoneman** [comment]
It seems to be working for me, at least as far as I can actually control
