### ISSUE TITLE
Regex Match

### ISSUE THREAD

**Issue by diboy2** [calzoneman/sync#243]
I'm sorry I'm not familiar with regex. How do you make the smiley using ":)"? I tried using [:)] but it gives two jpeg images instead. I really tried to read the regex manual but the manual is confusing.

**Comment by calzoneman** [comment]
Many characters in regular expressions have sprecial meanings (those characters are listed [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FGlobal_Objects%2FRegExp)).

If you want to actually match the character itself, escape it with a backslash (`\`).  If you want to match `:)`, you must use the regular expression `:\)`.

For future trivial questions like this that aren't actually bugs/suggestions for the software, feel free to ask in [IRC](http://webchat.6irc.net/?channels=synchtube) instead of opening a GitHub issue.

**Comment by diboy2** [comment]
Okay, sorry. :(
