### ISSUE TITLE
Private messaging

### ISSUE THREAD

**Issue by nuclearace** [calzoneman/sync#246]
I've also been getting this request a lot. I was thinking some syntax along the lines of `/msg username message`. Or it could be something that is in the drop down for users. 

Private messages from others could be highlighted a different color than that of regular nickhighlights. Although a problem I see is people not knowing the difference and typing a regular chat message in reply to a private message. 

Another possibility is what some chat clients do and open another tab. Perhaps extending the `usercount` div to include a tabbing feature. Which would let users tab between main chat and private chats with users. 

Another thing, do you log private chats between users? I have conflicting feelings about it.

**Comment by calzoneman** [comment]
I have been considering this.  If it does get implemented, it will be tabbed.  Unfortunately it's going to be a while because I have so much to do already.

**Comment by PseudonymRS** [comment]
Tabbed private messages are definitely my number one request for Cytube at
the moment, and I'm really glad you're considering it.

**Comment by calzoneman** [comment]
I will certainly push to have it ready by v2.4.  No promises though.

**Comment by calzoneman** [comment]
Just an update on this, I've been pushing back new features to focus on improving the existing code.  I still intend to implement this feature, but it still may be a bit before it gets done.

**Comment by calzoneman** [comment]
Further update: this shouldn't be hard to implement from a backend perspective.  The main roadblock at the moment is designing a UI for it.

A simple solution is to place tabs next to the connected user count, but then when there are too many tabs that breaks down.  If you have any suggestions I'll be gladd to consider them

cc @PseudonymRS

**Comment by PseudonymRS** [comment]
Perhaps an icon next to the connected users count representing the main
chat, and an icon next to a user's name (similar to the AFK and leader
symbols) representing the private message tab.

**Comment by Twirlie** [comment]
I would suggest either having the tabs start a new row when more chats are open or putting the private chats in a dropdown from the navbar.

**Comment by calzoneman** [comment]
I've been thinking about this recently, and I don't think I'm going to implement it.  It's not that the code would be too difficult (I already have a mental plan of how it would work), but I think adding this feature would extend CyTube to functionality it shouldn't have.

It was always my intent for CyTube to do a small set of functions and do them well, rather than try to create my own internet island.  It makes sense for there to be a channel chatroom, because people will almost surely want to discuss the media being synchronized.  However, private messaging is of a more private nature and is better handled by existing software, including IRC, XMPP, AIM, etc.

So that's where I stand right now, I'd rather focus on improving the robustness and reliability of existing features instead of adding new roles to the server.
