### ISSUE TITLE
Chat Filter m/;-?\)/g incorrectly matches ")

### ISSUE THREAD

**Issue by ipatjolvur** [calzoneman/sync#260]
A chat filter with the `g` flag and the regex `;-?\)` incorrectly matches the chat text `")`.  Similarly, the regex `:-?\(` incorrectly matches `"(`.

**Comment by calzoneman** [comment]
Can you provie the following please?
1. Server/room on which you're having the issue
2. Chat message that I can send as a test case

I just added the regular expression `;-?\)` to an empty channel, and tried sending various combinations of chat messages containing `)`, but none of them were filtered.

Keep in mind that the filters in the list are evaluated sequentially on a chat message.  I can't know for sure without seeing the room, but perhaps a previous filter is affecting the message in a way that it then matches this regex.

**Comment by calzoneman** [comment]
Oh, I see, you literally meant to include the `"`, hold on.

**Comment by calzoneman** [comment]
Ah, I figured it out.  The reason it's matching is because `"`, like other HTML/JavaScript entities, gets filtered to an escaped HTML entity (specifically, `"` becomes `&quot;`).

If you want to be sure that you're only matching the emoticon, prefix the regex with `(^|\s)`.  This will only match at the beginning of a message or after whitespace.
