### ISSUE TITLE
Throttling Bug

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#277]
The rate limiter will prevent videos from being added when it shouldn't. As an example, just now, Naoko tried to add five videos after a 20 minute video (it had been at least 30 minutes since she last added something). Only the first video was actually added, the other four got `queueFail` responses with "You are adding videos too quickly" as the reason.

This doesn't happen every time, the expected behaviour happens most of the time, but it happens regularly enough that it's a definite issue. I'm not sure about steps to reproduce it; I'll let you know if I notice anything on my end but I suspect it's just a logic bug or a race condition in Cytube.

**Comment by nuclearace** [comment]
I ran into it too. I added `time.sleep(.51)` to naoko's  `_addVideoToList` as a temporary fix and it hasn't done it again.

**Comment by calzoneman** [comment]
Tracked this down with some test cases.  The burst cap wasn't being reset until you had exceeded it, regardless of how long you waited.

The chance of a human encountering such a case was extremely small because most people cannot add videos faster than the sustained limit anyways.  The reason it appeared nondeterministic to a bot is because the behavior depended on how much of your burst had been used up prior to cooling down.
