### ISSUE TITLE
Custom JS

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#28]
Hi, can we have "Custom JS" field in channel options, just like we have now "Custom CSS"? Many of channel owners want to make their channels more flexible and functionable using jquery (for example advanced layout change, emoticons panels etc.).

**Comment by calzoneman** [comment]
I'm not completely opposed to it, but I have a few concerns that it could be used maliciously.  Obviously this is less of a problem since it's restricted to channel moderators, but the possibility still stands that they could trick people into joining their channel and use JS to read cookies or redirect to something malicious.

The other problem is that most browsers make it tricky to embed 3rd-party JS.  I'll look into what options are available and get back to you.

**Comment by uchigawa** [comment]
I see this project as many independent servers with lower number of channels instead one big synchtube with hundreds of them. In small communities probability of doing bad things is rather low. So let's trust administrators, they can always ban bad people and channels :)

Also, from a technical point of view, it worked perfectly on synchtube and there was no problem with browsers. It would be very nice to have such an option.
