### ISSUE TITLE
Videos Added Out of Order

### ISSUE THREAD

**Issue by awused** [calzoneman/sync#285]
I've noticed when multiple videos are added in a row they'll often come back in a scrambled order. I know this is because of you making calls to Youtube in parallel but is it possible for you to make sure all the requests for a certain room happen serially?

Alternately some form of queue for requests ensuring that, even if they're worked on in parallel, they're completed in serial.

**Comment by calzoneman** [comment]
The playlist queueing already operates on a special kind of queue.  When a video is added, an item is added (or moved or deleted), the operation is appended to a list, and a recurring interval operates on the list.  For videos which are not cached, the property "waiting" is set to true for that item, indicating that it should not be processed (until the media lookup callback sets waiting to false).  I'm not sure why this is failing in your case, but it's difficult to find out because playlist additions are a convoluted mess of different cases.

Due to the nature of node.js I/O being asynchronous, it is impossible to natively block until a request completes, so I have to resort to manually enforcing order.

**Comment by calzoneman** [comment]
@Suwako I just applied this update to cytu.be, so you shouldn't see this issue anymore.

**Comment by awused** [comment]
I still see it. It's not really a high priority issue though. Just when you have time.

**Comment by calzoneman** [comment]
I'm afraid I'll need you to provide an exact reproducible test case.  I completely re-did the playlist manipulation queueing and thoroughly tested it with large playlists.  Without a reproducible demonstration of the issue there is no way I can possibly figure out what is happening for you.

**Comment by calzoneman** [comment]
Never mind, I made some tweaks to naokosimulator2013.js to flood the first 10 videos with no delay, and I believe I found the issue.  It actually has nothing to do with the playlist queue, which is properly implemented, it's a race condition with the database that I believe I've fixed just now.

**Comment by awused** [comment]
Yeah, Naoko does send the first ten videos with no delay. Then she waits a full second before going into a sustained 2 per second. Actually she's 20% slower than that, since without that 20% safety margin I was still running into occasional throttling.

**Comment by calzoneman** [comment]
My test bot waits 1050ms between additions (although I probably don't need to wait that long).  The timing is somewhat nondeterministic because of latency between you and the server (you might send messages at exact 1000ms intervals but due to network lag they might arrive closer or further apart).

**Comment by awused** [comment]
Yeah I know, that's why I included a safety margin. 20% happens to be the lowest one that I've yet to run into problems with.
