### ISSUE TITLE
Playlists Management and Wall suggestion

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#31]
What are the possibilities to add a simple playlists management (load/save) and a wall/shoutbox (do you remember it from synchtube)?

Currently we have only possibility to paste set of links separated with comma. It would make playlist management much easier. Moreover, it is impossible now to get set of links from active playlist. As for wall/shoutbox it will make better communication between all members of channel community - leave messages, announcements etc.

If it's possible, I propose to add to the right panel nav tabs with "search" (current "library" box), "playlists" and "wall".

**Comment by calzoneman** [comment]
I'm not sure what you mean by a shoutbox.  I never extensively used Synchtube; most of the UI for this project is a mixture of my own ideas, the little I know about Synchtube, and inspiration from a closed-source Synchtube clone that I frequent.  Is that like the MOTD?

You can queue YouTube playlists of the form `http://youtube.com/watch?list=(listid)`.  I just checked the Help page and realized I haven't documented this feature.  Updating the Help page is on my TODO.  I would really prefer not to implement my own playlist feature because in my opinion that dangerously approaches overcomplicating things, and my intention with this project was to keep it simple (from a UX point of view as well as code complexity).

**Comment by uchigawa** [comment]
I mean something like on the picture below - messages that can be left by every registerd user. It was very popular on synchtube and known as "wall". Actually it's something between chat and simple forum.

I understand you don't want to overcomplicating things, I will try to make it on my own but it's hard. I'm not a programmer actually.

About playlists: I don't know how to get a list/array of links from the current playlist. If you decide not to implement this feature, I would like to have a liitle help from you how to do it.

![wall](https://f.cloud.github.com/assets/4163505/387273/d0c90f6e-a6bc-11e2-8d0b-b5dfe6d4d562.png)

**Comment by calzoneman** [comment]
Yeah, adding what is essentially a Twitter clone inside my Synchtube clone is not what I was going for.  You're  welcome to fork it and add that yourself.

> About playlists: I don't know how to get a list/array of links from the current playlist. If you decide not to implement this feature, I would like to have a liitle help from you how to do it.

There's currently not a way to do this other than to shut down the server and cause it to dump channels to disk.  It shouldn't be too hard to add something to return them all as a comma separated list.  I might do this because you're not the first person to ask about it.

**Comment by uchigawa** [comment]
> It shouldn't be too hard to add something to return them all as a comma separated list.

This is what I want. Even if you not implenent playlists, it would be nice to have such possibility if I decide someday to fork.

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/e5b61ef91c5a1adbcdc309d4d3aeed1142a4e0f3
