### ISSUE TITLE
JWPlayer mp4 files only sync with an active leader

### ISSUE THREAD

**Issue by Kirtaner** [calzoneman/sync#321]
See title. Syncing works, but only with an active leader.

**Comment by Kirtaner** [comment]
Also when clicking "refresh media" the player only starts up again once the whole video is buffered. Strange.

**Comment by calzoneman** [comment]
Re: title issue- this is expected behavior.  When you're queueing anything with jwplayer, the server knows nothing about the link being added (whether or not it's a livestream, duration of direct linked files, etc.) so I simply don't synchronize serverside.  It was suggested in the past that perhaps I could add an interface to manually tell the server to synchronize jwplayer videos (and tell it how long they are), which I'm not entirely opposed to, but I'd have to find a way to add this without making the playlist controls even more of a clusterfuck than they already are.

Re: second comment, that sounds like a JWPlayer issue, you can try their help forums but that's not something I can control.  I'm just calling `play()` on the API, how that's implemented is hidden to me.

**Comment by Kirtaner** [comment]
If the active leader refreshes during a JWPlayer file, it goes to the next playlist item.

Perhaps something like MediaElements.js would work out better for static files? JWPlayer is still great for custom RTMP streams. http://mediaelementjs.com/

**Comment by calzoneman** [comment]
I mean I could, but I'd rather not go adding dependencies willy nilly when I have something that works.  I can try to look into working around the leader refreshing issue but it won't be top priority.

**Comment by calzoneman** [comment]
@Kirtaner Actually thanks for suggesting that, I might look into it in light of recent events.

**Comment by calzoneman** [comment]
As of 3.0, serverside synch with JWPlayer is supported by specifying a length when adding the link.
