### ISSUE TITLE
Questions about library data storage

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#33]
1. If the same video was played couple of times, each time a new record is adding to the database table, or each video has only one record?
2. What exactly are "seconds" and "duration" columns in the code below? What is the difference between them?

`var query = "INSERT INTO chan_{1}_library VALUES ('{2}', '{3}', {4}, '{5}', '{6}')"
        .replace("{1}", channame)
        .replace("{2}", media.id)
        .replace("{3}", media.title)
        .replace("{4}", media.seconds)
        .replace("{5}", media.duration)
        .replace("{6}", media.type);`

**Comment by calzoneman** [comment]
1. Entries with the same id will not be duplicated.  When a channel is loaded, the library is cached locally in a Javascript object keyed by id.  When videos are added, it is checked if the ID is in this object, and if it is, the cached data will be used instead of querying the media provider API.  The database is only updated if the ID is not found in the library cache.
2. The `seconds` column is an integer, whereas the `duration` column is a formatted time (for example `2:04`).  Looking back at the code, I am no longer using the `duration` column (the `Media` constructor generates the formatted time from `seconds`) so it can be removed.

**Comment by uchigawa** [comment]
Thanks, that's what I wanted to know! I looked into the code and that `duration` column bothered me.

And thank you for taking my previous ideas and suggestions into consideration.
