### ISSUE TITLE
About html5 video tags and webm 

### ISSUE THREAD

**Issue by jlkwy** [calzoneman/sync#344]
Any plans to give us full webm support? Both as the main video and as gif replacement to post in chat. I tried to make some regex for it but it looks like cytube removes the <video> tag.

Thanks.

**Comment by calzoneman** [comment]
1. WebM support for the active video is an idea I would consider.  As far as I know, virtually every modern browser supports WebM/VP8 so playback support should not be an issue.  However, there remains the issue that for serverside synchronization to work correctly, it has to know how long the video is.  As far as I know, there is not an easy way to do this besides parsing the video stream or asking the user to input the duration (which is what is currently required for serverside JWPlayer synch).
   If I allow the client to specify the duration (either manually or by creating an invisible tag and reading the duration), this opens up the possibility for trolls to fake the duration as a large number to jam up the playlist.  If you have ideas about this, please let me know.
2. I'll have to look into it a bit more before I remove the `<video>` tag from the XSS blacklist.  I don't think it's any more insecure than the whitelisted tags, I believe that the HTML sanitizer executed on chat messages should prevent most vectors for compromising a filter that inserts a `<video>` tag (for example, `<video src="$1"></video>` with the replacement `$1 = '" poster=alert("lel")'` shouldn't work because quotes are changed to HTML entities), but I want to make sure that people who add the filter carelessly won't be exposing their users to arbitrary javascript.

EDIT: Alternatively, I suppose, I could detect and allow webm links as emotes.

**Comment by jlkwy** [comment]
I'm no web dev I can't really help on that. I know that 4chan reads their duration pretty easily since you just have to hover the mouse on the thumbnail to see it. Maybe getting the duration is easy on there because the files are all <3mb, I don't know.

Thanks for looking into it. Webm is love, webm is life.

**Comment by calzoneman** [comment]
> I know that 4chan reads their duration pretty easily since you just have to hover the mouse on the thumbnail to see it.

Getting the duration on the client side is easy- just create a `Video` with the desired URL as the source, then check the duration.  The problem is that this has to be communicated to the server, and this opens the opportunity for a malicious user to send a fake video length in order to troll a channel.

I'll see if there's any easy way to get the duration serverside.

**Comment by datagutt** [comment]
You can use this library for getting metadata for videos (though, this requires installing ffmpeg on the server):
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#reading-video-metadata
