### ISSUE TITLE
Chat Filters containing escaped parentheses do not match text

### ISSUE THREAD

**Issue by ipatjolvur** [calzoneman/sync#347]
on http://cytu.be

A chat filter containing \( or \) in its regular expression does not match text containing an un-escaped ( or ).  I don't know if this was intentional to encourage people to migrate their smiley filters to the v3.0 Emotes, but it could be classified as a bug for some other potential filter uses.

To duplicate:
1. Create and save a chat filter containing an escaped parenthesis.
2. Type text in the chat box that contains a parenthesis that should match the filter's regex.  The filter will not match the text.

**Comment by calzoneman** [comment]
This actually has nothing to do with emotes.  It has to do with the built in message processor that strips HTML from messages.

What's happening is the parentheses are being converted to HTML entities before any user-defined filters are considered (i.e. `(` becomes `&40;`).  This (among other replacements for symbols like angle brackets and quotes) was originally to prevent users from performing XSS attacks on poorly constructed filters.

I'll have to think about the best way to handle this case. Since the HTML entity is visually the same as the original parenthesis, but is a different string, it confuses people who are trying to filter parentheses (similar for `<` being encoded to `&lt;` or quotes becoming `&quot;`).  I see a couple immediate options:
- I could have the filter preprocessor apply these encodings automatically to filter sources, but that might cause issues for people trying to chain filters (since a filter's _output_ may contain unescaped characters)
- I could have the filter UI detect the characters that are encoded and warn the user

I'm open to other ideas.

**Comment by ipatjolvur** [comment]
The Emotes dialog does not accept an Emote name containing a non-escaped parenthesis, either.  I was going to open a separate issue, but it might be related to what you said.  For instance, when entering `:)`, `:-)`, `:(`, or `:-(` as the Emote name, the boxes go blank as if it was accepted, but a row does _not_ appear in the Emotes table, and the name's text is _not_ converted to its image when typed in the chat box.  On the other hand, the Emotes dialog _does_ accept `:\)` yet still fails to convert that text in the chat box.

**Comment by calzoneman** [comment]
Now the emotes thing is a bug, because I tricked myself with the HTML entities.  It should automatically escape symbols that are special characters in regular expressions, but apparently that breaks parentheses in the validator.

**Comment by ipatjolvur** [comment]
> Now the emotes thing is a bug

Separate issue, then: #348
