### ISSUE TITLE
Emote names containing a pipe symbol interpret it as a regex

### ISSUE THREAD

**Issue by ipatjolvur** [calzoneman/sync#349]
On http://cytu.be, an emote with the name `:|` (pipe symbol for mouth) returns the following in the chat box:

Input: `text1 :| text2`
Output: `text1 <image> | <image> text2 <image>`

Is this a bug, or is it intentional so that emote names with the same image could be combined into 1 Emote entry?

**Comment by calzoneman** [comment]
It was originally intended that all characters that have special meaning would be escaped so that emote codes are literally what you type in to make the image come out.  It appears I somehow missed that one.

However, other people had asked me about providing alternative names for the same image, so I'm unsure whether I will fix this (or add a warning message about the pipe symbol).

**Comment by ipatjolvur** [comment]
Unfortunately, similar 3-image output occurs when the Emote name uses an escaped pipe `:\|`.  Also, using the pipe's HTML entity `&124;` makes the Emote only match the exact text "&124;" and not the pipe.  As it stands, there isn't a way to use the pipe as part of a name in the chat box input.

**Comment by calzoneman** [comment]
That's expected, because the backslash is itself escaped.

**Comment by ipatjolvur** [comment]
I'll make ones with a lowercase L and a capital I in the meantime.  Thank you.

**Comment by calzoneman** [comment]
Also, with regard to HTML entities, the only reason that mattered for filters is because certain characters are explicitly converted to HTML entities to prevent poorly-constructed chat filters from being afflicted with XSS vulnerabilities.
