### ISSUE TITLE
Failed to parse MP3 links

### ISSUE THREAD

**Issue by C0mkid** [calzoneman/sync#350]
"Failed to parse link. Please check that it is correct" getting this error when I try to add MP3 links to the playlist

**Comment by calzoneman** [comment]
Yes, this is because there is no default handler for MP3 links.  I am considering a way to embed raw audio and video files in the future, but there are a few issues that need to be worked out before this is possible, such as a way for the server to know how long the file is.

What you can do for now is add the link via JWPlayer, that is type in the link as `jw:http://blah.com/whatever/song.mp3` and then a text box will open up asking you to manually input the length.

[This page](https://github.com/calzoneman/sync/wiki/CyTube-3.0-User-Guide#supported-media-providers) documents all supported formats of input links.

**Comment by C0mkid** [comment]
Ah that's a shame, I know that PHP has a library called getID3 which supports a myriad of formats and can find the length for some even with a partial file (like .mp4, I've done this before)

I'd also suggest that maybe digging into Chrome's source code may help, I see that when I open up the MP3 before it has even finished streaming the whole file it knows the length. And also maybe this helps? http://www.kirupa.com/forum/showthread.php?181438-Calculate-the-length-of-a-streaming-mp3-Easy

**Comment by calzoneman** [comment]
@C0mkid Getting the duration of a video or audio file is easy in the browser, the problem is determining it on the server side.  I can't simply read it in the browser and send it over the wire, because that would allow a clever user to fake the wrong duration.

You could argue that this behavior is fine because there is a setting for maximum duration, but I still don't like the idea of someone being able to fake the duration of a file they add.

The other option is to use a server side library (e.g. ffmpeg) to extract the information, I just haven't really spent time to look into this.

The other issue of course is that while MP3 is pretty globally supported, video and audio format support across browsers is pretty unreliable.  This is why I specifically added a flash fallback for the H.264 files served by Vimeo, but I'm not sure this flash fallback would work for other formats.
