### ISSUE TITLE
Make it more obvious that being the leader grants you the ability to seek through videos

### ISSUE THREAD

**Issue by CoolOppo** [calzoneman/sync#353]
I have been using CyTube for quite a while now, and not until just now did I find out how to seek through the video. I am the type of person who likes tinkering with things, and despite digging through all of the settings, I never found it. I felt pretty dumb when I found out how easy it actually is, but how else would I find out to right click on my username and click "make leader"? And that's if I had known I could right-click on users in the first place. (See #352 for my other suggestion.)

**Comment by calzoneman** [comment]
The ability to right click users is indicated in the [user guide](https://github.com/calzoneman/sync/wiki/CyTube-3.0-User-Guide#chat-box).  Being able to seek the video is listed in the [FAQs](https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#how-do-i-seekpause-the-video--it-keeps-jumping-back).  I am willing to add a clause to the 3.0 user guide about what leader does (I believe the 2.x guide had this and it just never got ported over).

Closing this because it's not really a suggestion, it's just a complaint.  If you have specific suggestions for how it should be made "more obvious" (other than updating the user guide), then I can reopen and we can move forward from there.

**Comment by CoolOppo** [comment]
I did make one suggestion; I referenced the other issue. I didn't mean to
come off so rudely, sorry about that.

**Comment by calzoneman** [comment]
Well, your other issue offers a suggestion for making the menu more obvious, but this ticket implied that once you discovered the menu, it was unclear that leader granted you the ability to seek the video.  Is that a correct interpretation?

**Comment by CoolOppo** [comment]
Yeah, I agree that I didn't really state my solution. I just wanted to
apologize about that, and I was adding that just because it relates.

**Comment by calzoneman** [comment]
I'm not upset with you, I just can't really do much about it without outside ideas.  Since I designed the software, it's hard for me to judge something as obvious or not obvious.

**Comment by CoolOppo** [comment]
Yeah that's totally understandable. Another idea I just had is having the person who has the highest rank (and who is online) be the current leader.

**Comment by calzoneman** [comment]
I don't want anyone to be leader by default.  Having a client be leader is prone to synchronization issues due to network latency and buffering.  It's far superior to have the server keep an accurate time unless you need to seek or pause.

The server keeps track of the time regardless of whether there is a leader, so if you need to seek, you can simply give yourself leader, seek, then remove leader.

**Comment by CoolOppo** [comment]
What if instead, the video was only synchronized when the leader explicitly
changed their time in the video?

**Comment by calzoneman** [comment]
That still poses some issues.  Not all of the player APIs have a specific event for when a user seeks the video, only an API for retrieving the current time.  Because of this, there's no way to tell if a purposeful seek was done, or if the client's player is at the wrong time and needs to be synchronized to the server.

I know for a lot of people who used synchtube.com it's difficult to adjust to the idea of there not being a leader at all times, but I believe it is a superior mode of operation.
