### ISSUE TITLE
Can't add video from vk.com

### ISSUE THREAD

**Issue by rumours86** [calzoneman/sync#354]
Can't add video from vk.com

**Comment by calzoneman** [comment]
vk.com is not on the [supported media providers list](https://github.com/calzoneman/sync/wiki/CyTube-3.0-User-Guide#supported-media-providers).  Furthermore, upon visiting their site, it appears to be a social network rather than a video hosting site, so it's unlikely that they provide the API necessary to be able to embed and synchronize the video.

If they provide an embed code, you can use the custom embed feature to manually embed an `<iframe>` or `<embed>` of the video, but it won't synchronize.

If they did provide an API for controlling the video player, I would still need enough demand to justify adding it.  It's not worth the development time and added code complexity to add a video player that one person will use.
