### ISSUE TITLE
About an old issue;

### ISSUE THREAD

**Issue by 537** [calzoneman/sync#355]
I found issue #17 on Google while searching how to bulk add videos to a certain playlist, I'm wondering if there's a way and also if this has anything related?

**Comment by calzoneman** [comment]
If you comment on an old issue, I will receive a notification for it, so I'd prefer you comment on existing issues in the future instead of opening duplicates.

For a while in a previous version, CyTube supported adding multiple links at once.  This was before I supported saving and loading playlists.  However, this method of adding videos posed a number of internal issues, so after I added support for saving and loading user playlists, it was removed.

The best way to add a lot of YouTube videos at the same time is to create a YouTube playlist.  The best way to add a lot of videos of mixed type at the same time is to add them individually to a channel, save the playlist to your account, and then queue that playlist at a later time.

**Comment by 537** [comment]
I'm sorry about that, the issue was over a year old and it was closed.

Thanks though, I guess I have to add them manually or perhaps code a script for this, since there isn't one anywhere at all.

**Comment by calzoneman** [comment]
If you can get all of the video types and IDs as JSON, you can use [this](http://pastebin.com/etkXtLw1).

**Comment by 537** [comment]
I have all of the videos as links on YouTube, I suppose the IDs are after "watch?v=" - How do I get them as JSON? And what does the Pastebin you linked me to do?

**Comment by calzoneman** [comment]
You can use this in your browser

``` javascript
links="comma separated list of links";
i=0;links.split(",").forEach(function(link){setTimeout(function(){$("#mediaurl").val(link);queue("end");},(++i)*3000)});
```

I don't intend to add the comma queue feature back, but I may improve user playlist management in the future.

**Comment by 537** [comment]
What does that do?

**Comment by calzoneman** [comment]
Splits a list of urls, adds each one with a 3 second delay to prevent getting throttled.

**Comment by 537** [comment]
Sweet. Thank you.
