### ISSUE TITLE
Incorrect permitted characters prompt

### ISSUE THREAD

**Issue by sillybear25** [calzoneman/sync#356]
Entering a username with one or more non-permitted characters results in the prompt

> Invalid username. Usernames must be 1-20 characters long and consist only of characters a-z, A-Z, 0-9, -, _, and accented letters.

However, accented letters are not permitted. I didn't perform an exhaustive check, but it seems that neither pre-composed accented letters[1] nor combining accents[2] are permitted in the username field.

Either the username should accept accented letters or the prompt for invalid usernames should be changed to more accurately reflect the set of characters accepted in the username field.

[1] I tested a few from the "Latin-1" codepage, specified by ISO 8859-1 and Unicode code points U+0080-U+00FF
[2] I tested a couple from the "Combining Diacritical Marks" codepage, specified by Unicode code points U+0300-U+036F

**Comment by calzoneman** [comment]
Currently only non-accented letters, numbers, underscores, and hyphens are permitted.

When I started working on CyTube 3.0, I originally wanted to support a fuller character set, but due to internal complications I dropped it.  I thought I reverted all of the prompts, but this one slipped through, apparently.
