### ISSUE TITLE
console messages need to be patched up

### ISSUE THREAD

**Issue by benzap** [calzoneman/sync#357]
Voting information is being passed through the console, so voting isn't anonymous. It would also be helpful if I wasn't banned as a result of exposing such issues.

Thanks.

**Comment by calzoneman** [comment]
This is a somewhat confusing ticket.

First of all, voting information for **polls** is not logged anywhere.  Voteskips on playlist items are logged to each channel's log to allow moderators to punish vote trolls.  There is no "console" involved anywhere in this process.

Secondly, I am not responsible for the moderation actions taken in individual channels.  I develop the software and manage hosting for http://cytu.be, but for the most part I do not interfere with individual channels' moderation policies.  I do not ban people from the site as a whole for suggestions or bug reports.

I'm sorry you encountered a crappy channel owner, but unless many other people agree there is no good reason to log voteskips, that is the way it will remain.

**Comment by benzap** [comment]
Hey calzoneman,

I guess I wasn't that clear on what the problem was, or maybe i'm misinterpreting what areas you have control over.

If you bring up the javascript console during the vote polling, there are console.log messages which include information on who is voting on what. It's clearly visible from within the console. 

The messages take the form of something along the lines of console.log("chatmsg", object), where object contains foo.username, foo.msg. One of the messages passed through the console was along the lines of 

username=<person who voted>, msg="<span>something about voting</span>User <person who voted> voted on X"

By overloading the console.log command, you can basically include your own UI elements using dotjs to display this information whichever way you like.

I thought the vote polling was a part of cy.tube? I've seen the same functionality on other channels. I posted a little code snippet on the channel exposing it even more. I can't remember exactly, but it was along the lines of

```
console.log = function(key, obj) {
   if (obj && obj.msg && obj.msg.indexOf("<span>Vote Msg</span>" == 0) {
      console.error(obj.name + " : " + obj.msg);
   }
}
```

which effectively kills all logging and makes it easy to just see what people are voting on within the console. It probably would have been smarter to just post the issue here, instead of posting a foolish console script.

One easy way to fix the problem would be to just remove those console.log messages exposing this information. This information shouldn't get passed to people without the proper privileges anyways. It would mitigate the problem, but I don't think it fully resolves it, since I could just inject my own functionality to retrieve that information.

I'm not a seasoned developer, so maybe i'm not aware that maybe this isn't a big issue. So bare with me please.

Regards,

Ben

**Comment by calzoneman** [comment]
The socket frames being printed is because SOCKET_DEBUG is set to true on the client. Nonetheless, it is not default behavior for the server to emit chatMsg frames when poll voting occurs.

Is it possible that the channel owner has used channel JavaScript to bind an extra handler to poll buttons to emit chatMsg frames from the client when voting occurs (thus triggering the server to rebroadcast them)? I won't be home until tonight, but I will need to see a channel in which this happens in order to investigate further.

If it is a private channel, you may PM me on IRC or email me at the address listed on http://cytu.be/contact

**Comment by calzoneman** [comment]
Also, you're right, polls are a default feature of every channel. However, since channel owners have the ability to add client side JavaScript (which you can disable on your end by going to options and selecting "ignore channel js"), which some channels use to modify default behavior.

The snippet you posted makes me suspect that what I guessed above is correct and someone's js is sending a  hidden message when you vote. Try it in a vanilla (unmodified) channel and see if you can still get votes to leak.

**Comment by benzap** [comment]
I tried it in a vanilla public channel last night, I assumed it had been patched up. I suspected it had been fixed, but I guess it has to do with the custom code that was used in that particular channel (/r/fullmoviesonyoutube)

It's possible the maintainer of that code fixed these console.log calls on his side, I believe the maintainer is named 'bdizzle,' who also felt the need to ban me.

Thank you for the explanation

**Comment by calzoneman** [comment]
fullmoviesonyoutube has pretty heavy customization. In the future, you can go to options and disable channel js to turn off these customizations for your client.
