### ISSUE TITLE
Can't pause videos

### ISSUE THREAD

**Issue by krisztian1997** [calzoneman/sync#358]
I tried playing some videos from dailymotions on my own channel and when I click pause on the video, it pauses for a bit then resumes again after ~2 seconds.

**Comment by ghost** [comment]
That is because the video is synced to the server and the server doens't pause the video.

If you want to pause the video, you give yourself leader, and then pause it (this will also pause it for everyone else in the room).

You can give yourself leader in the menu which appears when you right click on a name in the left side of chat.

**Comment by nuclearace** [comment]
Yes what @cellistoctavia said. In order to pause a video on a channel you must click on your name and select give leader, this will allow you to seek/pause the video.

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#how-do-i-seekpause-the-video--it-keeps-jumping-back
