### ISSUE TITLE
large chat emotes break auto scrolling

### ISSUE THREAD

**Issue by sammoth** [calzoneman/sync#360]
We have some oversized chat emotes (larger vertically than one line of text) and when posted into the chat, the chat doesn't automatically scroll down enough to show them, and (not sure if it's related but) the image also loads half a second after the message is shown despite being cached.

This happens on Chrome only*, the cache seems to be slower somehow.

**Comment by calzoneman** [comment]
Can you provide an example of an image with does so?

I know that chat doesn't scroll enough for non-cached images because the scrolling happens before the browser loads the image and sets the size.  However, for cached images this is not an issue.

I tested this with a rather large image on both Firefox and Chromium and after the initial caching I had no problems with scrolling.

**Comment by sammoth** [comment]
Yes you can see examples in our chat if you are here now http://synchtube.6irc.net/r/kpg2# (may be a somewhat silly)

This is one example image:
https://www.googledrive.com/host/0B3dM3srfBf8XbHhUbDhJcGs1X0k/images/aing.gif
or https://www.googledrive.com/host/0B3dM3srfBf8XbHhUbDhJcGs1X0k/images/aing3.gif

**Comment by calzoneman** [comment]
I've modified the chat handler to attach an event listener for image loads and re-scroll.  This should fix the issue regardless of whether it's cached.

I'll have to bug bush to update synchtube.6irc.net.

**Comment by sammoth** [comment]
Thanks very much that was super quick! Might paste the fix into our channel in the mean time. Much appreciated!
