### ISSUE TITLE
berrymotes - buildEmoteMap inserts berrymotes_colour_data.js even if already inserted

### ISSUE THREAD

**Issue by jamesmanning** [calzoneman/sync#382]
buildEmoteMap is called both initially (via waitToStart) and when refreshing emote data. Since it does an unconditional insert of the script tag for berrymotes_colour_data.js, that ends up getting run multiple times.  This doesn't break anything, just not needed.

not sure if this is something fixed 'upstream' already or not, but it seems like the insert might be something to pull out to its own function and just call before buildEmoteMap in waitToStart?

![image](https://cloud.githubusercontent.com/assets/225626/3452081/0f323a5c-01aa-11e4-8fc7-166e6560acd3.png)

**Comment by calzoneman** [comment]
This is not a core feature, it's brought in from an external script that I maintain for certain channels.  I almost hesitate to use the word maintain because I do as little work as required to keep it running.

Berrymotes had a pretty big refactor upstream so the script being used is still an old version.  I can look into this specific issue.  For reference, the script being used: http://jupiter.cyzon.us/~cyzon/berrymotes.js
