### ISSUE TITLE
G+ Video not recognised

### ISSUE THREAD

**Issue by Billzy** [calzoneman/sync#391]
Link for the video.
https://plus.google.com/photos/118168297075505999151/albums/6017192162717927553/6020383507545464754

**Comment by calzoneman** [comment]
I think having multiple videos in one album causes issues.  I'll see if there's anything I can do about it, but it's a bit tricky:

When you go to a link for a video in an album, the returned page has data for all the videos in the album.  I'm going to have to try and improve my ~~algorithm~~ hack for determining where the right data is for the requested link.

**Comment by calzoneman** [comment]
I think I might have figured it out.  It looks like the album has 120 videos, but downloading the HTML only gives valid data for 100.  I think Google only displays 100 at first, and loads the rest in with AJAX.

The solution is to limit your album size so that all videos can be returned on one page.
