### ISSUE TITLE
Fuzziness when it comes to Queue Adding

### ISSUE THREAD

**Issue by QuillOmega0** [calzoneman/sync#392]
It would be great if fuzziness was added to the queue addition. What i mean is if the link doesn't match exact conditions when adding, it refuses to queue.

IMHO cytube can be smarter and take links that include playlist variables and such from youtube links/vimeo links, and extract or figure out the video that needs to be queued; like BT

**Comment by calzoneman** [comment]
Which kinds of links are you running into problems with?  I'm pretty sure most of the providers are using regex matching for the base URL and ignoring extra parameters.

**Comment by d-dd** [comment]
Today I encountered a Youtube link which didn't queue successfully.
https://www.youtube.com/watch?list=RDn7pac86e8Ho&v=3bEikMqDd3M
For some reason Youtube gave me(*) a url with the video id at the end, when usually it's at the front. This was from browsing within Youtube, so I'm not sure what happened, and I couldn't reproduce the anomaly. It's probably not worth accounting for unless it starts happening more often.

*The url that was in the address bar.

EDIT:
The url pattern where the list comes first happens when I click a playlist link from the three-by-four video selection that comes up after a video finishes playing.

**Comment by calzoneman** [comment]
https://github.com/calzoneman/sync/commit/735b2fcd07ab0d1139768e1fa4a1a603d48d0362
