### ISSUE TITLE
WebRTC via PeerJS?

### ISSUE THREAD

**Issue by frenchja** [calzoneman/sync#401]
Thanks for the work on this, first of all.

What are your thoughts on integrating [PeerJS](http://peerjs.com/) or [EasyRTC](http://easyrtc.com/) for an MST3K or Rifftrax style system for audio?

I found an older EasyRTC based plugin for NodeBB, which is also NodeJS based: https://github.com/Schamper/nodebb-plugin-webrtc-old/

**Comment by calzoneman** [comment]
I have a few questions:
1. What is the use case for this?  What would users be able to do with WebRTC support on CyTube that they cannot already do?  How many people would this benefit?  One of my main concerns with adding new video providers is that there needs to be enough demand for the feature to justify the cost of implementing it and maintaining it in the future.
2. Would the proposed functionality fit well with CyTube's current functionality?  One thing I have tried to avoid is creating a piece of software that tries to do too many different things, instead focusing on making it the best available software for synchronizing video and chatting.  I'm not opposed to adding new features, but I also don't want to integrate a new service into CyTube that would be better off as a standalone service.
3. Are there any security concerns with WebRTC?  I want to ensure that I wouldn't be exposing users to remote code execution, malicious data transfer, etc.

**Comment by frenchja** [comment]
1.  Very small, admittedly.  WebRTC only enables a group of users to voice chat and would be inappropriate for large channels.  
2.  Certainly fits in with the goals of synchronized viewing, by enabling more methods of communication while viewing.  You raise a good point though and it's probably better that I maintain a fork specific to my site and merge in any of your updated code to allow you continue focusing on the existing code.
3.  Certainly.  The code is [open](https://github.com/peers/peerjs) but the risk is proportional to the amount of code increased over base CyTube.  Some concerns are mitigated with the use of TLS on the site.

**Comment by calzoneman** [comment]
Yeah, I don't think this is something I want to pursue for CyTube right now.  There are plenty of websites and other software for voice and video chat, so I feel like implementing the service itself would be adding weight to CyTube without much novelty.  I've tried to focus on integrating with existing services rather than implementing audio/video services myself because this keeps the server light on resources and easier to maintain.

Maintaining an integrated text chat instead of offloading to IRC is an example of a decision that has cost me a lot of development time and provided not too much benefit over just integrating an existing chat service (emotes, HTML, and filters are nice and not supported by IRC, but they are computationally expensive in comparison).

I do appreciate the suggestion, and you're of course welcome to add this in a fork.
