### ISSUE TITLE
Set width and height for emote img elements.

### ISSUE THREAD

**Issue by henke37** [calzoneman/sync#415]
Set the width and height attributes for the img elements generated for emotes. This avoids relayouts as the browser guesses the image size wrong and/or shows the alt text while waiting.

There are multiple benefits to this. The biggest one is that relayouts are annoying for the reader. It is also inefficient to do relayouts. Relayouts is also the underlaying cause of issue #360.

**Comment by nuclearace** [comment]
You can use channel css to set the `.channel-emote` sizes

**Comment by henke37** [comment]
Not good for when there is more than one size of emote. One instance I frequent has many sizes.

**Comment by calzoneman** [comment]
Emotes are from external image sources, there is no way for the client to know what the size of the image is in advance.

**Comment by henke37** [comment]
The keyword there being "client". The server can easily track it as two additional db fields. Emotes are not expected to change size, so it's fine to cache the data.

As for who to populate the database, it is easy for both server and admin client to just load the image and record the dimensions.

**Comment by calzoneman** [comment]
> it is easy for both server an admin client to just load the image and record the dimensions

Client perhaps, but I will not let the server download arbitrary images.  It's an easy denial of service vector-- just find a link to some massive file, rename it to `.png` and tell the server it's an emote.

**Comment by calzoneman** [comment]
Although that also raises the question of how channels with hundreds (and in some case, thousands) of existing emotes are going to update them

**Comment by calzoneman** [comment]
My point is not that it's a bad idea at face value, just that there's a lot to be considered that doesn't make this a trivial fix
- How is the size data determined? (this one is probably the easiest to solve by the person adding the emote downloading and extracting the size, as mentioned above)
- What if an image's size does change?  Does the emote creator then have to re-add the emote?
- What happens to the hundreds of channels with existing emotes?
- What happens if someone tries to import a list of emotes that was exported before size was introduced?  If the same principle of having their browser download the image and extract the size is applied, it could take a long time for the import to finish
- What happens if the image `width` and `height` conflict with the `.channel-emote` CSS?

**Comment by henke37** [comment]
If images change in size then the browser will be forced to rescale them to the old size. As I wrote, emotes are not expected to change in size. Readding/adjusting them will have to be done manually.

Existing channels and dumps can run a batch converting script. While "a long time" is relative, it shouldn't take more than a couple minutes for a couple hundred images. It is fine, if it is done on the client and only once. It can easily be automated and done in multiple batches to keep peek loads low. And until it's been run, the generated html fragment can simply omit the attributes.

if the css conflicts then the same thing happens as for other applications: I duno, one of them has to win. But if there is a style that conflicts then they really should either fix the emote set to not conflict or change the css to remove the rule, it is poor form to resize images on the client anyway.

One could add a warning to the emote management UI if the size is "unsupported". Channel admins shouldn't be forcing one size and adding another. It really is a corner case that should never happen in properly managed channels.

**Comment by calzoneman** [comment]
I'll take a look at this this weekend

**Comment by calzoneman** [comment]
Alright, so I looked into this, and I've run into an issue.  Perhaps since you're the one who opened this suggestion, you may be able to provide some input.

If an emote has a size that is larger than the `max-width` specified by `.channel-emote`, then before the image loads, Firefox (haven't tested chrome) uses the width and height specified by the `width` and `height` attributes (specified by the emote data) for the size of the empty image.  As soon as the image loads, the CSS rule is applied, the emote is downsized, and chat is now scrolled wrong.

I can't really think of a good solution to this that isn't even hackier than the current method of just waiting for images to load then scrolling chat.  If you have one, let me know.

You can argue all you want about how people shouldn't add emotes that are larger than the `max-width` of the `.channel-emote` class; that isn't going to stop people from doing it.  And when they do, people are going to blame me and not the channel owner ("it used to work until calzoneman changed it").

**Comment by henke37** [comment]
It is easy enough to cap the set size yourself on the server as long as you know what the limit is. If people are currently resizing emotes using css then they will have to stop doing so. It should be easy to automatically migrate any channels that has such a rule, css is machine readable.

As for the scroll hack, I don't see any reason to remove it, even after this, at least one browser can be set to forcibly resize images to fit the alt text when showing the text.

**Comment by calzoneman** [comment]
> If people are currently resizing emotes using css then they will have to stop doing so.

I should have mentioned, the `.channel-emote` CSS rule is not only for channel owners.  I also added it for people like myself who don't want to disable emotes, but would like to scale them down to a smaller size so they take up less room.

> It should be easy to automatically migrate any channels that has such a rule, css is machine readable.

The maximum size mandated by this rule can not only vary over time per channel as the stylesheets are updated, it can also vary per user!  This does not make it a good candidate for a limit to be tracked serverside and enforced upon emote creation.

The only thing I could think of would be to try to grab the sizing rules from JavaScript and compare those with the emote size, but that seems pretty hacky.

> As for the scroll hack, I don't see any reason to remove it

If I'm not removing the "wait for images to load and then re-scroll" hack, then I don't really see a point in putting the effort into releasing and maintaining the changes requested in this issue.

**Comment by Xaekai** [comment]
> If people are currently resizing emotes using css then they will have to stop doing so. 

No.
