### ISSUE TITLE
Video.js support?

### ISSUE THREAD

**Issue by Billzy** [calzoneman/sync#418]
Any chance of seeing Video.js (https://github.com/videojs/video.js) ever being implemented to replace the normal players?
It would make a players like YT/Dailymotion ad-free (https://github.com/benjipott/video.js-dailymotion) and it would also make the player more consistent like audio volume.
It allows you to skin the player aswell which could be nice for extra channel customization (http://designer.videojs.com/).

edit: Lots of plugins are available incase some services aren't supported here https://github.com/videojs/video.js/wiki/Plugins

**Comment by calzoneman** [comment]
I have considered vjs as a replacement for the current system used for raw file playback (native HTML5 with JWPlayer fallback), however I don't think I want to use it for YouTube/Dailymotion.

In the case of YouTube, replacing the YouTube UI with the vjs UI removes some buttons that get more use than you might think (like/dislike, watch later, turn on/off annotations).

For both YouTube and Dailymotion, as far as I can tell, vjs doesn't provide an interface for quality selection (I didn't see one in the repo you linked me for Dailymotion support, please correct me if it does actually support this).

> it would also make the player more consistent like audio volume

CyTube already has code in place to synchronize volume between players when switching videos.  If you discover a particular transition between players that does not synchronize, please report it and I will fix it.  This happened recently due to a bug with the Dailymotion API, which I subsequently reported to them and has been fixed.

**Comment by Billzy** [comment]
Fair point on the UI part even though that was one of my main annoyances :D.
http://www.casedasole.it/video/YT.html <-some random demo has quality selection so the support is already there for atleast YouTube.
For DailyMotion, i'm pretty sure the same thing can be done by basicly doing the same as YouTube but changing a few quality parameters up.

I don't think any player out there supports the like/dislike and annotations functions (i'm guessing from looking at YT's api) that it's not supported but seems like a small tradeoff to me.

And for the volume sync, i haven't really noticed anything lately because i had them on max volume so this might be an obsolete addition, sorry bout that.

**Comment by calzoneman** [comment]
> I don't think any player out there supports the like/dislike and annotations functions (i'm guessing from looking at YT's api) that it's not supported but seems like a small tradeoff to me.

For me as well (I never use those buttons) however I tried disabling them once via the YouTube API (it allows you to disable various UI elements) and I got several complaints from people who made a good point that it's more convenient than having to open the video in a new tab and then like it.

I guess I don't really see what the benefit is to using vjs for YouTube and Dailymotion since their player APIs are actually pretty sane (in contrast to, say, Soundcloud).  If it does actually block ads (the dm plugin you linked before seems to be a wrapper around Dailymotion's chromeless player, does that really not show ads?  I'd have to test it) then that would be a benefit, but besides that it seems like a decent amount of work just to re-implement features that already exist in the current players.

I'm still considering using vjs for raw file-types (ffmpeg, Google Drive, Google+, Vimeo) in version 4.0, but I don't really see a reason to use it in place of officially supported APIs.

**Comment by Billzy** [comment]
You can visit http://jsfiddle.net/gh/get/library/pure/benjipott/video.js-dailymotion/tree/master/example with adblock off, no ads will be displayed (atleast for me).
They normally show as a preroll and every 5 minutes or so after that.
I tried it on both FF and Chrome so it could be html5 or chromeless related.

**Comment by calzoneman** [comment]
Closing this since video.js is the player used for Drive/Google+/Vimeo/Raw files now.
