### ISSUE TITLE
Subtitels in Raw Movie

### ISSUE THREAD

**Issue by shpedro** [calzoneman/sync#430]
First Thing.

This is a great project... Thanks for all your work.

Second thing, i'm looking for a way to add subtitles to raw videos. 
Is there any way to do that now?

**Comment by calzoneman** [comment]
There is not currently a way to do that.  As far as I'm aware, there is no way for HTML5 `<video>` to extract subtitles from the video file itself, you would have to provide a subtitle file for use with a [`<track>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/track).  That would be something I would be willing to add, but I don't have any demo files and I actually don't even know how to extract the subtitles from a video.  There would have to be corresponding documentation changes to inform people how to do so, and then people would have to upload their subtitles file somewhere as well as the video.

**Comment by calzoneman** [comment]
See also: https://developer.mozilla.org/en-US/docs/Web/API/Web_Video_Text_Tracks_Format

**Comment by shpedro** [comment]
Hello,

I was just specking about the <track> element, not getting the subtitle of
a raw video.

The functionality will be to add a external subtitle source that the
jwplayer can read in the Raw video functionality.
That can work like subtitle or wiki/facts for the raw video source.

Em 26/01/2015 01:20, "Calvin Montgomery" notifications@github.com
escreveu:

**Comment by calzoneman** [comment]
Adding a field to the meta information of a raw video to store the link to subtitles, and then using that field to add a `<track>` to the HTML5 player (or passing it to JWPlayer for people with shit browsers that don't support HTML5 natively) is not technically difficult, and is something I'm willing to do.

The issue here is that I don't own any video files with subtitles, and I don't know how to extract a VTT file from them even if I did.  Since I don't know how to do so, I also couldn't explain to end users how to do so.  I can find demo videos with associated VTT files that I can use for testing, but the feature is worthless if I can't explain to anyone how they would use it with a video file that they have.

My request to you is that you explain to me how, if I had a video with subtitles, I would generate the VTT file to be used with the `<track>` element.

**Comment by shpedro** [comment]
Yes I understand.

The feature is a bonus, everything else that exists now don't change except
for a small button or field that people can use o set the src for the
subtitles.

For people that use Subtitles is a common job to do in any player, to set
the subtitles path.
I think they will understand that online...
And don't need to be VTT, can be a normal str.

If this helps: http://www.storiesinflight.com/js_videosub/

Don't know if that is possible or not, or if you can see if is something
that users demand.
If is just for me... I can "Burn" the subtitles to the movie, no problem :)

Thanks for the reply, and I really like you project...

2015-01-26 18:08 GMT+00:00 Calvin Montgomery notifications@github.com:

> Adding a field to the meta information of a raw video to store the link to
> subtitles, and then using that field to add a <track> to the HTML5 player
> (or passing it to JWPlayer for people with shit browsers that don't support
> HTML5 natively) is not technically difficult, and is something I'm willing
> to do.
> 
> The issue here is that I don't own any video files with subtitles, and I
> don't know how to extract a VTT file from them even if I did. Since I don't
> know how to do so, I also couldn't explain to end users how to do so. I can
> find demo videos with associated VTT files that I can use for testing, but
> the feature is worthless if I can't explain to anyone how they would use it
> with a video file that they have.
> 
> My reques
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/calzoneman/sync/issues/430#issuecomment-71507434.

## 

Pedro Ferreira
about.me/shpedro
[image: Pedro Ferreira on about.me]
  http://about.me/shpedro

**Comment by calzoneman** [comment]
I took a look at this and ran into some issues.

I got captions to work fine in the native HTML5 player, however when I attempted to integrate them into JWPlayer, I ran into issues with mixed active content (loading a VTT captions file from a plain HTTP website while accessing cytube over HTTPS).  In addition, JWPlayer captions are riddled with [cross-domain restrictions](http://support.jwplayer.com/customer/portal/articles/1403679-crossdomain-file-loading) that would require special CORS settings on the websites hosting the VTT files.

I don't really want to release something that works for some people but not for others, and I also don't want to have to explain CORS to anyone who wants to add captions to their videos, so for now I think hardsubbing is the best available option.

I'll take a look at this again when I'm doing the video player for CyTube 4; maybe I can figure out a better way to handle it.

**Comment by shpedro** [comment]
Ok,

I completely understand the problems.
I will burn the subs tin to the video for now, and waiting for the Cytube 4.

Thanks.

2015-01-31 21:53 GMT+00:00 Calvin Montgomery notifications@github.com:

> I took a look at this and ran into some issues.
> 
> I got captions to work fine in the native HTML5 player, however when I
> attempted to integrate them into JWPlayer, I ran into issues with mixed
> active content (loading a VTT captions file from a plain HTTP website while
> accessing cytube over HTTPS). In addition, JWPlayer captions are riddled
> with cross-domain restrictions
> http://support.jwplayer.com/customer/portal/articles/1403679-crossdomain-file-loading
> that would require special CORS settings on the websites hosting the VTT
> files.
> 
> I don't really want to release something that works for some people but
> not for others, and I also don't want to have to explain CORS to anyone who
> wants to add captions to their videos, so for now I think hardsubbing is
> the best available option.
> 
> I'll take a look at this again when I'm doing the video player for CyTube
> 4; maybe I can figure out a better way to handle it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/calzoneman/sync/issues/430#issuecomment-72338739.

## 

Pedro Ferreira
about.me/shpedro
[image: Pedro Ferreira on about.me]
  http://about.me/shpedro

**Comment by shlomogoldberg** [comment]
⠀⢀⡤⠒⠉⠉⠉⠉⠉⠒⢄⣀⠔⠉⠉⠉⠒⠤⡀⠀
⡰⠋⠀⠀⠀⢀⣀⣀⣀⣀⣈⡇⠀⠀⠀⠀⠀⠀⠈⢆⠀
⠁⠀⠀⠠⠊⠉⠀⠀⠀⠀⠀⠉⠲⣤⠒⠒⠒⠒⠒⠬⣆
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢧⠀⠀⠀⠀⠀⠈⠑⢄
⠀⠀⠀⡰⣚⡭⠭⠭⠭⠭⠭⣟⠻⣍⠑⢇⠀⠀⢀⡲⢶⣯⣭⡵⣤⡀
⠀⠀⠺⠼⣥⠄⠀⣠⢤⣤⣤⡄⠉⠒⢝⢄⡇⠘⣽⣮⣥⣄⠤⣙⣾
⠀⠀⠀⠀⠀⣍⠑⠿⣿⣿⣤⡿⠀⠀⠈⢌⠇⡎⣾⣾⣿⣩⠀⠀⡸
⠀⠀⠀⠀⠀⠈⠑⠢⠤⠬⠭⣓⣒⣒⣪⠽⠃⢭⣍⣉⡉⠉⣉⣭⠊
⠀⠀⠒⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠔⠁⠀⠀⠀⠈⠳⣄⠈⠉⠁⠱
⠀⢺⠛⠥⠤⣀⡀⠀⠀⠐⠚⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⢻
⠀⠈⠓⢬⡑⠤⢍⣉⡉⠑⠢⠤⠤⠤⢄⣀⣀⣀⣀⣀⣀⣀⣠⢔⡳⠁
⠀⠀⠀⠀⠈⠑⠒⢄⡈⠉⠉⠉⠑⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠋⡸
⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠒⠒⠦⠤⠤⠤⠤⠤⠤⠤⠤⠤⠴⢺
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠴⠋⠓⢤⠊
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠤⠤⡠⠮⡀⢀⣤⠤⡀⣉⠒⢄
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢦⡀⠓⢺⢚⡩⣊⠴⠋⠁⠀⠀⠳⡀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢱⠀⠘⢅⣎⠀⠀⣠⠞⠀⢀⡀⠈⢆
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠜⡄⠀⠀⠉⠳⠴⡁⠀⡴⠋⢀⠖⠘⡄

**Comment by justjanne** [comment]
@calzoneman I have a demo of a small HTML5 player that supports Chrome, Firefox, IE8+ and Safari with subtitles at http://dl.kuschku.de/demo/player/ – including demo files in the standard format for subtitles (SRT).

One solution would be adding a proxy where cytube accesses the subtitle URL once and then mirrors the subtitle file for all users viewing the video in-stream.

(Currently on our channel on CyTube we are considering adding subtitle support through our channel JS, which isn’t exactly great, but our first tests worked)

**Comment by calzoneman** [comment]
Mirroring the subtitles may be a necessary evil, I was hoping to avoid it but browser security policy is such a nightmare that I might have to look into that.

Subtitles is at the bottom of the priority queue right now.  I'm working on rewriting video playback in general (including using VideoJS for file playback), which should make adding subtitles simpler in the future, but I have a lot of traveling coming up so realistically subtitle support is a long ways out.

**Comment by PinkysBrain** [comment]
@justjanne did you ever complete this? If so any chance of sharing? :) I'm particularly interested in support for videojs-ass.

PS. in a few months MSE support will finally get unlocked in Firefox. In theory at that point things like javascript MKV players and subtitle extraction should be possible across all major browsers. A lot more work than simply bashing in something like videojs-ass with a separate subtitle file of course.

**Comment by calzoneman** [comment]
I added subtitle support for Google Drive videos, but I haven't done it for raw files yet (it's somewhere in the endless TODO queue).  It could be a little tricky due to CORS issues (I ended up having to mirror the Google Drive subtitles on CyTube's server in order to get around this for Drive, but I'm not comfortable rehosting random text files from other peoples' servers).

**Comment by calzoneman** [comment]
Also, subtitle support for raw videos would likely be WebVTT since that is already an established web standard supported by VideoJS.  I'd rather not be forced to add plugins in order to play other subtitle files when they're easily convertable.

**Comment by calzoneman** [comment]
> PS. in a few months MSE support will finally get unlocked in Firefox. In theory at that point things like javascript MKV players and subtitle extraction should be possible across all major browsers.

I don't know about "most".  The reason H.264 is almost universally supported is that even if your browser can't natively decode it (and most can-- even I.E. should be able to), every modern flash player you can find supports it.  I don't think MKV has that kind of widespread support.

**Comment by PinkysBrain** [comment]
With MKV I mostly meant H.264 video encoded in MKV (together with audio and subtitles).

With MSE you can create a MP4 file in a memory buffer and play it. So you could parse the MKV, extract the subtitle files (to be rendered separately) and copy the H.264&audio into a mp4 bitstream to be played on the fly. Of course working at the bitstream level combined with seeking and buffering will be a major PITA, so as I said "in theory".

**Comment by calzoneman** [comment]
That sounds extremely hacky.  I'm sure someone will attempt that to get Hacker News cred at some point, but why not just re-encode with an MP4 container?  It's really simple and the tools already exist to do it.

**Comment by calzoneman** [comment]
Also, the discussion of MKV is off-topic for this thread.

**Comment by justjanne** [comment]
Well, MKV is not really off-topic, because it’s one of the few formats that allows proper SSA and ASSA subtitles.

Which are used by almost every anime subbing group. Writing a renderer for those in JS would be an amazing solution.

But then one would have to render those subtitles with canvas on top of the video, or with MSE.

**Comment by calzoneman** [comment]
This issue is specifically about including the ability to overlay subtitles over the video player.  If and when the time comes that most browsers are able to decode MKV natively (a JS decoder is out of the question-- the performance would be horrendous), then you should open a separate issue for "Ability to play MKV files".

On the topic of subtitles, can you please explain what the advantage is of supporting substation alpha files over WebVTT, under the assumption that MKV will not be playable in the near future?  WebVTT is already natively supported in some browsers (e.g. Firefox), and the fallback for browsers that don't natively support it is already included in the main distribution of video.js.  Adding substation alpha support would require either writing a decoder or importing an existing one and to my knowledge cannot be rendered natively in any browser.  There are plenty of converters from various subtitle formats to WebVTT so unless WebVTT lacks some really important features, I don't see the benefit of supporting other formats.

For now, the best option is to encode your video files to MP4/H.264 and convert your subtitles to WebVTT.  The planned implementation of raw file subtitles is similar to Google Drive, except there will be a UI to add subtitle files when adding the video (since there is not a way to extract these automatically).

**Comment by PinkysBrain** [comment]
ASS/SSA is prevalent, there is as of yet no converter for ass to vtt which preserves formatting (it might be possible with a ton of CSS, but I haven't see anyone say so conclusively) and there is already a fair amount of rendering code for it out there : 

http://www.kenshisoft.com/projects-resos/as3captionslib/
https://www.npmjs.com/package/videojs-ass

I'll copy paste the rationale for ass/ssa support from the late Mediacrush : 

SRT is very similar to VTT, and VTT has support natively via WebVTT. MediaCrush has a procedure for converting SRT to VTT for use on the web. However, ASS is a much more versatile subtitle format, with support for more interesting subtitles and effects. VTT/SRT, on the other hand, is a glorified closed captioning format.

PS. being able to do playback through VLC would solve ass support (and MKV for that matter) as well, since that's off topic I started a [new issue](https://github.com/calzoneman/sync/issues/501).

**Comment by calzoneman** [comment]
> VTT/SRT, on the other hand, is a glorified closed captioning format.

Isn't that basically what subtitles are? ;)

Anyways, I think I'm going to plan on just getting raw videos to work with webvtt first, then create a separate TODO item to investigate supporting other formats.  I'm very hesitant to pull in video.js plugins right now since video.js is in the process of a major version update from 4.x to 5.0 (so I don't want to add something and then have it break a month later when I upgrade to video.js 5.0).

**Comment by justjanne** [comment]
@calzoneman: What ASS and SSA do is far more than closed captioning.  
Just for reference some ASS examples:

![Example #1](http://fat.gfycat.com/MemorableGoldenAphid.gif)

![Example #2](https://i.imgur.com/wKZ7rNzl.png)

**Comment by calzoneman** [comment]
@justjanne I understand that SSA is more powerful than VTT (which is pretty basic)-- I just feel that the additional features it brings are more so extras than an integral part of the feature.  Hence, I think it is better for me to implement VTT captions first, since that can be done without any additional plugins, and then later once CyTube is upgraded to video.js 5 we can take a look at the available options for supporting SSA.

Currently I'm in the process of migrating the ffmpeg logic as part of my initiative to move metadata querying out of CyTube into a separate package for easier maintenance and reusability.  I'll probably take a look at implementing VTT captions as part of the process for integrating that library with CyTube.  In the meantime, if you require subtitles, CyTube can already show WebVTT captions for Google Drive, or you can hardsub.

**Comment by justjanne** [comment]
@calzoneman: As currently Google Drive support is bad anyway, we on our channel are going to rewrite the player used for that anyway (as we only use .mp4 files that we uploaded, we can just use the http://googledrive.com/host/<file-id> which gives the raw file), so I can just use a video.js plugin that supports those subtitles.

**Comment by calzoneman** [comment]
> As currently Google Drive support is bad anyway, we on our channel are going to rewrite the player used for that anyway (as we only use .mp4 files that we uploaded, we can just use the http://googledrive.com/host/ which gives the raw file), so I can just use a video.js plugin that supports those subtitles.

There shouldn't be any need to rewrite anything, the support for MP4 playback is already there.  Just add the MP4 link in CyTube and it will treat it as a file link and not Google Drive.

**Comment by justjanne** [comment]
Nope, it does not. It returns a "file extension is not .mp4, can not be played".

Also it does not support subtitles for raw movie files.

And the link times out after one hour. So, we’ll just let each user's browser request the link themselves, and add subtitles, etc directly there. We already changed a lot of the existing code on our channel anyway.

**Comment by calzoneman** [comment]
> Nope, it does not. It returns a "file extension is not .mp4, can not be played".

If the link does not end in MP4, but you are sure the format is correct, you can override the autodetection by prefixing the link with `fi:`, e.g. `fi:https://googledrive.com/host/blah`.

> Also it does not support subtitles for raw movie files.

That's correct, but you should be able to extend the current player and add that rather than rewriting the whole thing.

**Comment by justjanne** [comment]
Well, I am – I am just replacing the Google Drive player with a custom variant of the File Player, so it can automatically load subtitles ;)

**Comment by soredake** [comment]
https://github.com/Arnavion/libjass

**Comment by calzoneman** [comment]
Closing as a dupe since the work for #655 will support this feature request as well.
