### ISSUE TITLE
Support for PostgreSQL

### ISSUE THREAD

**Issue by soredake** [calzoneman/sync#438]
Will postgresql support in the future?

**Comment by calzoneman** [comment]
The next major version that I'm working on uses [knex](http://knexjs.org/) to interface with the database, which means that in principle SQLite 3, MySQL, or PostgreSQL could be used.  The only issue is that for SQLite 3 and PostgreSQL, neither has a case insensitive collation.

Since CyTube is case insensitive with respect to usernames and channel names, this creates a few challenges in interfacing with a database that is case sensitive, but to the extent that it won't create too much trouble I'll try to support it.

**Comment by Gelmo** [comment]
@calzoneman http://sqlfiddle.com/#!7/ae8f8/2

**Comment by calzoneman** [comment]
Yes, SQLite3 supports `COLLATE NOCASE`, I don't know the context of why I originally thought it didn't support case-insensitive collation.

Anyways, I'm not saying it's a blocker, I just wanted to point out that there are various behaviors of MariaDB that are hidden assumptions in the code so it's not as simple as changing out the connection pool, there is actually work involved to identify and ensure all these cases are accounted for in different databases (collation, on duplicate key updates, 0 values, how unicode is handled, etc.) -- even with only supporting one database type people occasionally run into compatibility issues among MySQL 5, MySQL 8, and MariaDB.

I probably won't be prioritizing this work in the current maintenance-mode branch; if I ever release a new version I would consider different database support for that.  If someone has a pressing need to not use MariaDB, I'm willing to review a PR within reason (I don't want to add support for 5 different DBs because that multiplies the maintenance work required whenever the database schema needs to be updated).  The approach would probably need to look like:

  1. Identify code paths that are directly issuing DB queries instead of going through a data access object.  Isolate those queries into their own DAO.
  2. Create an integration test suite for all DAOs to codify the current behavior.
  3. Investigate MySQL-specific behavior in `src/database/tables.js` and port it to the DB of choice.  Run just the schema generation on the new DB to troubleshoot incompatible schemas.
  4. Move simple queries to knex query builders.
  5. For more complicated queries, investigate how to implement it in different databases and make them abstract at the DAO level so that different implementations can be used for different DBs.
  6. Test.
