### ISSUE TITLE
Duplicates detection

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#45]
Currently channel can be spammed with the same video over and over, which leads to the channel crash.

**Comment by calzoneman** [comment]
How are you triggering the channel crash?  Allowing duplicate videos (in the sense of the same video being queued multiple times) is intentional, but I've never had a situation in which this killed the channel.

I need a procedure that I can follow to reliably reproduce the problem or else I can't debug it.

**Comment by calzoneman** [comment]
Any news on this?

**Comment by ghost** [comment]
I'll do some tests in a while.

**Comment by calzoneman** [comment]
If you're able to test locally, it would be most useful if you go to `server.js` and comment out/remove the `uncaughtException` handler so that a failure results in a stack trace.

**Comment by ghost** [comment]
Alright, tested it out, channel didn't crash and no failures were present in stack trace, even with script made to spam channel rapidly. Previously it must have been my PC fault, however, adding videos to the playlist should be limited somehow just to prevent griefing.

**Comment by calzoneman** [comment]
The antispam system for chat is very generalized, I can apply it to this too.
