### ISSUE TITLE
More advanced youtube search

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#47]
Is it youtube api limitation to have only 25 search results?

If not, and if you have some free time and want to improve it, you could make more advanced searching with results pagination and sorting by relevenance/upload date/view count/rating, just like on YT.

**Comment by calzoneman** [comment]
YouTube's API returns 25 results per page.  I'm just reading the first page because the YouTube search is intended to just be a quick convenience.  It's certainly possible to do what you're suggesting, but that would push this software further away from the UNIX philosophy of "do one thing and do it well".  YouTube's website will have a much better search function than anything I could implement directly into CyTube.

**Comment by uchigawa** [comment]
OK, I just wanted to know, I do not really use this feature.
