### ISSUE TITLE
Voteskip ratio miscalculation

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#49]
6 connected users
Ratio 0.6 -> 4.6 votes needed.
Ratio 0.5 -> 4 votes needed
Ratio 0.4 -> 3.4 votes needed
Ergo: (votes needed - 1) should be fine.

**Comment by calzoneman** [comment]
It's not a miscalculation, I was intentionally using a strict greater-than rather than an inclusive one.  There are arguments to both ways, but if I do program it such that 0.5 would result in 3 votes needed, I will change the default ratio to 0.51, because I think by default it should require a majority (3/6 is NOT a majority).

EDIT: To clarify, this is a discrepancy in definition.  You have defined the voteskip ratio to be the percentage of votes required in order for the vote to pass, whereas I defined it as the percentage of votes _that must be surpassed_ in order for the vote to pass.

**Comment by calzoneman** [comment]
Went ahead and changed this because I think most people would prefer your way.
