### ISSUE TITLE
Preload next video/catchup period

### ISSUE THREAD

**Issue by tigt** [calzoneman/sync#495]
Hey! Cytube is amazing, and handily beats Livestream in every area but one.

My friends and I aren't gifted with the best of internet connections; in particular the latency is awful. We'll get hung up when the video switches, and then play eternal catch-up with the video skipping ahead every couple of seconds.

It would be great if there was the ability to load the next video, paused, in an invisible container or something so the DNS fetch, TCP connection, and DOM initialization could happen ahead of time, then swap it and start playing.

If not, can we pause during a video, so our computers and connections can catch up? It's especially painful for videos with important beginnings or short total runtimes, which is what our channel specializes in.

**Comment by calzoneman** [comment]
> It would be great if there was the ability to load the next video, paused, in an invisible container or something so the DNS fetch, TCP connection, and DOM initialization could happen ahead of time, then swap it and start playing.

I have a few concerns about this.  A lot of the players that CyTube implements are very finicky about initialization.  For some, it's impossible to pause the video or set the volume before it starts playing, which means that if I initialized it in the background, it would spook people with a split second of audio.

Hiding the player might break certain player types (at least, I think that was the reason that the old "hide the player before opening a modal on Chrome" hack resized it to 1x1 instead of using CSS).  I'm also a little bit concerned about whether it would lag older hardware to start loading a second video.  It's an interesting idea that I might experiment with, but I'm not sure that the benefits (which I think would be marginal, if any) would outweigh the costs.

CyTube already waits 3 seconds before starting the timer on a video (actually, it starts the time at -3 seconds, and the client pauses the video to let it buffer until the time reaches 0).  This is sufficient to allow most people enough buffer time to be able to start on time, but ultimately if your connection is slower at loading the video than the rate at which the video plays I don't think any amount of technical trickery is going to save you.  It is worth increasing the sync threshold (click Options at the top, and increase the number from 2 to 5 or 10) for your browser to see if that helps.

> If not, can we pause during a video, so our computers and connections can catch up?

https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#why-cant-i-pause-or-seek-the-video

**Comment by tigt** [comment]
Excellent! Thanks for the actionable advice.
