### ISSUE TITLE
Video.js mangled names

### ISSUE THREAD

**Issue by kaba99** [calzoneman/sync#497]
Can you change www/js/video.js to unmangled version, so it will be possible to use some videojs plugins without problems with method and property names.

**Comment by calzoneman** [comment]
Can you give an example of a plugin which doesn't work currently?  I have not modified [video.js](https://raw.githubusercontent.com/calzoneman/sync/06347d6c257572386d09fbaa78ed306f599e529b/www/js/video.js) at all from the [officially distributed](https://vjs.zencdn.net/4.12.7/video.js) uglified version.  If there are plugins that don't work with this, I see 2 potential problems:
- The plugin is relying on a non-public API (i.e., undocumented features)
- Video.js is uglifying essential property names that many plugins need to function &mdash; this would be an issue you should bring up with the video.js team

I'm willing to minify the non-uglified source code myself for a small increase in filesize as long as it doesn't break anything, but if plugins are relying on undocumented APIs that seems fragile and I don't want to continually have to 'fix' video.js in order to support plugin developers' hacks.

**Comment by kaba99** [comment]
I tried to use [videojs.progressTips.js](https://github.com/mickey/videojs-progressTips) to show tooltips with the time on progressbar.
This plugin [checks](https://github.com/mickey/videojs-progressTips/blob/master/dist/videojs.progressTips.js#L11) player.techName property to check if current player is Html5 player, and if it is not, it quits. 

The current video.js version uses player.Ua property instead of player.techName, so plugin always quits because player.techName is undefined.

**Comment by calzoneman** [comment]
The video.js developers have stated their reasoning for why the `techName` property is not available [here](https://github.com/videojs/video.js/issues/1234).  I could swap out the dist file for the dev version, but I would like to reiterate that since access to that variable is explicitly not supported by the developers of video.js, it may disappear or be renamed at any time.

For what it's worth, the exact feature provided by that plugin has been merged into core for video.js 5.0 (which is not fully released yet, but I plan to upgrade CyTube to it when it is): https://github.com/videojs/video.js/pull/2255.

**Comment by kaba99** [comment]
Thank you for your answers, I think it would be better to keep things as they are and wait for 5.0 video.js.
