### ISSUE TITLE
Exit if connection to database failed

### ISSUE THREAD

**Issue by katanacrimson** [calzoneman/sync#500]
As on tin.  Currently the event is marked "fatal: true" and logged as such (or console.dir'd, I've not looked at the code) but it clearly is a situation where the application _should_ terminate and tell the user to check the database et al.

**Comment by calzoneman** [comment]
Can you clarify what you mean by database failure?

I disagree that a database failure should terminate the application.  Brief database failures can occur from time to time, for example when MySQL/MariaDB is restarted due to a package upgrade.  This causes any operations that attempt to access the database during that time to fail, but that's fine, the overall state of the application is not affected and for any user-initiated actions that failed because the database wasn't available, they get an error message and can just try again.

As for telling the user to check the database, database failures are logged to the error log.  It's not 100% consistent, but my general rule of thumb is that anything logged to the error log indicates "you should probably look into why this is broken".

**Comment by calzoneman** [comment]
The only situation in which I think it would be appropriate to terminate the application due to a database failure is if the initial database login fails on startup, or the tables fail to be created on a fresh installation.

**Comment by calzoneman** [comment]
Closing after 3 days with no response.  If you have anything further to add, feel free to leave a comment.

**Comment by katanacrimson** [comment]
apologies - work things kept me busy. twas the former - on startup, database login failed because some certain moron didn't have the database server running.  so, if that happens, should probably be more of a refusal to start and a bitch-slapped admin, imo.

**Comment by calzoneman** [comment]
Yep, failing if the initial login fails on startup seems reasonable.  I'll reopen to track that.
