### ISSUE TITLE
VLC plugin support

### ISSUE THREAD

**Issue by PinkysBrain** [calzoneman/sync#501]
I know on the modern web it's considered non kosher, but it would be nice to be able to queue items with "vlc:" to have them played back with the VLC plugin (also like file: it should be non picky about extensions, VLC can figure it out).

This would open up MKV files for playback and would provide an alternative way to support subtitles.

**Comment by calzoneman** [comment]
I've had a few people ask about this before, and I don't really want to allow people to queue files that are only playable by a third party browser plugin.  It ruins the UX when you get those stupid "plugin not found" boxes instead of it "just working" (like most video types do on most modern browsers).
