### ISSUE TITLE
Support for Twitch VODs

### ISSUE THREAD

**Issue by LuigiBlood** [calzoneman/sync#511]
With friends, I would like to be able to watch Twitch highlights/past broadcasts, I tried to use the embed function (with lack of sync function, which is understandable), but it's not working, the embed itself doesn't want to appear at all.

**Comment by calzoneman** [comment]
> but it's not working, the embed itself doesn't want to appear at all.

Can you paste the embed code you tried to use?  IIRC twitch gives you plain HTTP embeds, which means that if you try to embed it when loading CyTube over HTTPS (https://cytu.be/r/test) then it won't work due to browser security policy.

As for properly supporting VODs, I'd have to check whether they have a syncable API.

**Comment by LuigiBlood** [comment]
I used the Embed Live Player share:

```
<object bgcolor="#000000" data="http://www.twitch.tv/swflibs/TwitchPlayer.swf" height="378" id="clip_embed_player_flash" type="application/x-shockwave-flash" width="620">
    <param name="movie" value="http://www.twitch.tv/swflibs/TwitchPlayer.swf" />
    <param name="allowScriptAccess" value="always" />
    <param name="allowNetworking" value="all" />
    <param name="allowFullScreen" value="true" />
    <param name="flashvars" value="channel=fangamer&amp;auto_play=false&amp;start_volume=25&amp;videoId=v8347022&amp;device_id=ce298840d9a1caf4" />
</object>
```

I removed the link at the end (with it, it doesn't change anything anyway). (Also added some clarity, as it's only in one line)

**Comment by calzoneman** [comment]
I confirmed that I can load that (although as you mentioned, it won't synch).  I suspect that the reason it doesn't load for you is the reason I gave before, which is that if you load CyTube over HTTPS, you can't load a Twitch embed since they serve them over plain HTTP (browser security policy blocks the embed).

There is supposed to be an explicit error message in this condition, but it looks like I may have broken that when I added the untrusted content confirmation box.

**Comment by Xaekai** [comment]
Dropping these here for convenience.
https://github.com/justintv/Twitch-API/blob/master/v3_resources/videos.md#get-videosid
https://github.com/justintv/Twitch-API/blob/master/embed-video.md

**Comment by calzoneman** [comment]
I've created the pull request with the implementation of this.  It is currently installed on beta.synchtube.me for testing.

**Comment by calzoneman** [comment]
This is now live.
