### ISSUE TITLE
Logout should use a POST request

### ISSUE THREAD

**Issue by henke37** [calzoneman/sync#515]
Links should never cause problems if they are automatically visited.

Of course, the logout form can be a form with just one button that is styled to look like a link. It just shouldn't be one under the hood.

**Comment by calzoneman** [comment]
> Links should never cause problems if they are automatically visited.

Browsers should never automatically visit links, but regrettably some of them do and hence this is a problem.

I took a look at this a while back when I was adding the CSRF token to logouts, but I remember running into issues with CSS due to swapping the plain `<a>` tag with a `<form>`.  I'll have to take a second look at it.

**Comment by henke37** [comment]
The HTTP standard says that all GET requests should be safe, without any cost to the user and that automated tools may issue them without confirmation from the user.

**Comment by calzoneman** [comment]
I'm aware of what the standard says and that's why I'm agreeing to look into this instead of closing it as a wontfix.  "Browsers should never automatically visit links" was my opinion, if it wasn't clear.

**Comment by calzoneman** [comment]
This is resolved now that that commit has been merged.
