### ISSUE TITLE
Cooldown on voteskips

### ISSUE THREAD

**Issue by henke37** [calzoneman/sync#518]
Perhaps users shouldn't be able to voteskip several times in a second?

**Comment by calzoneman** [comment]
Can you explain what you mean by this?  Voteskips are handled internally the same way as polls-- a user can only voteskip once per video.  Even if they bypass the UI and send the socket frames manually this should be idempotent.

**Comment by henke37** [comment]
I mean that people can voteskip several videos in a row in a second in a thinly populated channel.

**Comment by calzoneman** [comment]
Hmm, throttling voteskips seems like it kind of defeats the purpose of even having voteskips.  The server shouldn't care if you happen to dislike 10 videos in a row and desire to skip them all (there are legitimate use cases for this, not just "some troll decided to voteskip everything").

Of course, every channel has a different philosophy on how voteskips should be treated, and that's why channel admins have the ability to both toggle it on/off and adjust the vote ratio required to skip a video.
