### ISSUE TITLE
Cytube connection

### ISSUE THREAD

**Issue by darkchiefy** [calzoneman/sync#524]
On my laptop computer, I am currently unable to go to any cytube channel. It states that it is disconnecting and trying to reconnect. It had been trying to do that for 3 hours and no luck. Yet, it works on apple mobile devices though I can't see the video on them. What am I suppose to do?

**Comment by calzoneman** [comment]
It would be helpful to me if you could take a screenshot of the JavaScript console from the device where you are unable to connect.  You can access this in Chrome by pressing `Ctrl+Shift+J` or in Firefox by pressing `Ctrl+Shift+K`.  That will help me figure out what is going wrong, since a couple people have had this issue today.

**Comment by calzoneman** [comment]
OK, I think I have found the issue.  You simply need to clear your cache and refresh (Ctrl+F5).
