### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#525]
Hey if your reading this. I keep getting a troll constantly spamming paragraphs of "NIGGER" and he sometimes does this for hours no even joking the longest he did it for was 3. I  make the chat registered accounts only which slows his spam down but he still does it. I also slower down the throttle but that doesn't stop him spamming yet. Is there a possibility that you can make the register require email verification or make people wait at least 1 minute before their guest account is made? It will really test his patience and he will eventually give up. He's been doing this for the past week and it's getting really sad for him doing this. Is there any spam filters at all? My channel is one of the most popular on CyTube and I don't want it ruined by a annoying racist 13 year old troll. He's also been doing this to other channels not only he's been running my channel but also CyTube. Yes I have IP banned him but he still comes back. Is there a way to somehow reverse his DNS and make his dynamic IP useless? The admin of the trees network told me about it but I don't really understand this type of stuff. His user name is simon so message him about it if you want and hopefully he'll tell you how to do it https://www.treesnetwork.com/

**Comment by calzoneman** [comment]
I'm sorry that you've been getting harassed.  It seems every month or so another person with no life shows up to taunt various CyTube channels.

Let me try to answer your questions in order.

> Is there a possibility that you can make the register require email verification or make people wait at least 1 minute before their guest account is made?

Clarifying note: guest logins are limited to 1 per 60 seconds for each IP address; however, if a troll has access to a large pool of IP addresses that he can easily change among (such as a VPN service), it is trivial to bypass this.  In the past I have preferred not to require email verification of registrations, both because it is extra work to implement and because it's inconvenient for legitimate users.  It's worth noting that any restrictions I add to registration to slow down and annoy trolls will also slow down and annoy legitimate users, which is unfortunate.  However, given that this happens semi frequently, it may be something that I need to investigate adding in some form.

Another option is to still allow registrations without an email address but add a new "verified user" rank for users who have confirmed their registration via email, and allow channel owners to optionally only allow verified users to chat.

> Is there any spam filters at all?

Implementing a generic spam filter is difficult, both because different channels have different ideas about what constitutes spam, and because any attempts to pattern match spam can be worked around by changing the contents of the spam.  I have been considering implementing a "spam filters" feature, which is similar to chat filters but instead of replacing the text, it would allow you to autokick/mute/ban anyone who triggers it.  In the meantime, you could implement similar functionality by having a bot monitor chat and automatically react to messages you consider to be spam.  If you would like some help with this, I'm sure someone in IRC could help you.

Another option I have considered in the past is allowing channel owners to set a minimum time that new users must wait before sending a chat message for the first time in the channel.  There are some technical details that I would need to work out for this, but if the demand is present I will look into it.

> Yes I have IP banned him but he still comes back. Is there a way to somehow reverse his DNS and make his dynamic IP useless?

The spammer in question was using a variety of IP addresses from different ranges owned by different companies.  It is not a case of someone with a dynamic home IP address, which is easy to detect and block since all IPs are in the same range.  Rather, they are using proxies to hide their real IP address.  It is difficult to detect when the same user is ban evading by using a different IP address and username with a proxy.  However, I did go ahead and add firewall rules for some of the proxies that the spammer was using.  Unfortunately it is not as simple as just blocking proxies, as it is difficult to get a list of them and also may block legitimate users who are using a VPN/proxy to bypass country restrictions.

On a side note, for this kind of communication I would prefer if you contact me on IRC or via email in the future, since it is an issue of site administration and not an issue with the software itself.

**Comment by Xaekai** [comment]
I'll take useful tools for $1000 Alex. What are Regular Expressions?

![image](https://cloud.githubusercontent.com/assets/594255/10866788/9330b382-7ffe-11e5-832c-f727e551c57d.png)

Top Navbar -> Channel Settings -> Edit -> Chat Filters

He's a very basic "nigger" filter as a filter export line.

```
{"name":"Check your digital racism","source":"\\bn[yi1]+ggg*[e3i]+rr*[sz]*\\b","flags":"gi","replace":"nugger","active":true,"filterlinks":false}
```

You should really learn how to use the tools provided if you want to run an active room.

**Comment by calzoneman** [comment]
Please send me an email for any future concerns about this.
