### ISSUE TITLE
Sync does not check for X-FORWARDED-FOR header

### ISSUE THREAD

**Issue by jaw-sh** [calzoneman/sync#528]
My IP is always 127.0.0.1 on my server because it's accepting traffic from a proxy pass. I have set the appropriate headers but I can't get the client's true IP. This is causing tons of issues.

What is the appropriate way of doing this?

**Comment by ghost** [comment]
Did you set x-forwarded-for in the headers from your proxy?

**Comment by jaw-sh** [comment]
@bush6 Yes.

```
# LOLCOW.TV

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    server_name lolcow.tv;

    listen 80;
    listen 8081;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;

        proxy_cache_bypass $http_upgrade;
        proxy_pass http://localhost:8080;
        proxy_redirect off;
    }

    location /socket.io {
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Conection $connection_upgrade;

        proxy_cache_bypass $http_upgrade;
        proxy_pass http://localhost:1338;
        proxy_redirect off;
    }
}
```

**Comment by calzoneman** [comment]
The x-forwarded-for header is only read by the webserver, not the socket.io server. It's not expected that the socket.io connection will be proxied (and there are very few reasons to do it that way). I can add this tonight, but I've never tested proxying the socket.io connection so there could be some other side effect.

If you need to resolve this urgently, you can either copy the logic from src/web/middleware/x-forwarded-for.js to src/io/ioserver.js or connect directly rather than using an nginx proxy for socket.io.

Calvin

**Comment by jaw-sh** [comment]
@calzoneman Maybe this explains my situation better. I absolutely cannot allow the socket.io (I think that's what it is that's causing this) to be unproxied because leaking the true IP of this server would be a massive security risk.

I'll try your suggestion though, thanks.

```
127.0.0.1 joined Autism
Accepted socket from 127.0.0.1
127.0.0.1 signed in as Hellblazer
127.0.0.1 joined Autism
Accepted socket from 127.0.0.1
127.0.0.1 logged in as hoodLOLCOW
127.0.0.1 joined Autism
Accepted socket from 127.0.0.1
127.0.0.1 logged in as hoodLOLCOW
127.0.0.1 joined Autism
Accepted socket from 127.0.0.1
127.0.0.1 joined Autism
Accepted socket from 127.0.0.1
127.0.0.1 joined Autism
Accepted socket from 127.0.0.1
127.0.0.1 joined Autism
127.0.0.1 signed in as daphny
Cleaned old aliases
Unloaded channel Autism
Accepted socket from 127.0.0.1
127.0.0.1 signed in as God
127.0.0.1 joined Autism
Unloaded channel Autism
Cleaned old aliases
Cleaned old aliases
Cleaned old aliases
Accepted socket from 127.0.0.1
127.0.0.1 joined Autism
Unloaded channel Autism
Accepted socket from 127.0.0.1
127.0.0.1 joined Autism
Unloaded channel Autism
Cleaned old aliases
Accepted socket from 127.0.0.1
127.0.0.1 signed in as God
127.0.0.1 joined Autism
Unloaded channel Autism
Accepted socket from 127.0.0.1
127.0.0.1 signed in as God
127.0.0.1 joined Autism
Unloaded channel Autism
Cleaned old aliases
Cleaned old aliases
Accepted socket from 127.0.0.1
127.0.0.1 signed in as God
127.0.0.1 joined Autism
Unloaded channel Autism
```

**Comment by calzoneman** [comment]
> I absolutely cannot allow the socket.io (I think that's what it is that's causing this) to be unproxied because leaking the true IP of this server would be a massive security risk.

Yes, it is socket.io.  I'll look into adding this since a handful of people may want to proxy socket.io, I'm just mentioning that unless you have a really good reason to proxy it, you should consider not proxying it.

As a side note, if exposing your IP address would be a "massive security risk", I would caution against running CyTube on it, since I develop under the assumption that the end-user already knows the server's IP address.  Reverse proxying will hide your IP address from incoming requests, but there are cases where CyTube will make external network calls to user-provided addresses, such as if you enable the ffprobe module for adding HTML5 videos to the playlist.

**Comment by jaw-sh** [comment]
@calzoneman Got it. Thanks a lot. Never worked with io.js or websockets before but all I had to do was change L137 of ioserver.js to;

```
    var ip = sock.client.request.headers['x-forwarded-for'] || sock.client.conn.remoteAddress;
```

And then re-run that npm build server command again.

Thanks mate.

**Comment by jaw-sh** [comment]
Cheers, thanks for letting me know.

**Comment by hey-red** [comment]
@calzoneman maybe add this option in config?

**Comment by calzoneman** [comment]
Yep, I'm planning to add an option for it, I just haven't prioritized it since this is a rare use case-- as I mentioned, unless you have a very good reason to proxy socket.io, you should not.
