### ISSUE TITLE
use videojs for rtmp player

### ISSUE THREAD

**Issue by draculaaa** [calzoneman/sync#532]
the current player has issues with any resolution above 480p (appears to crush it down to 480p)

sync uses videojs for raw video, so why not use it for rtmp aswell?

**Comment by calzoneman** [comment]
I recall that there was some issue (I don't remember exactly what) with RTMP playback when I was in the process of migrating to use video.js so I elected to stick with the existing player.  Video.js has since been updated to version 5.0, so perhaps whatever problem there was is fixed now, I'll have to check.
