### ISSUE TITLE
No warning when CSS file size exceeds limit (20KB), deletes data.

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#538]
Hi. I run a CyTube room which uses a lot of CSS, and the style changes a lot for certain events.
Whenever you're working on the CSS and it exceeds the max file size (20KB), it removes whatever is left at the end of the file. This produces a lot of bugs in the CSS and I think a warning when the file size has exceeded the limit would be nice. Perhaps the limit could be bumped up a bit higher too?

I'm using Google Chrome 46 on Mac OS X El Capitan, but I have had this issue across many different systems/browsers, so I don't think it's a problem with the platform I'm on.

Thank you so much for maintaining this. It's brought a lot of people I know together and has provided hours of entertainment \o/

**Comment by calzoneman** [comment]
Yes, adding a warning would be useful.  Increasing the limit is being considered for the future, but it probably won't happen for a while.

Initially, custom CSS was limited to externally linked stylesheets, but inline CSS was added as a convenience for channels that need only basic styling and don't want to bother with finding a file host for the stylesheet.  It's kept in RAM and sent over socket.io rather than served as a file from the webserver, hence the small limit.  I hope in the future to rework the way custom CSS is handled.
