### ISSUE TITLE
Redirect Loop on /account

### ISSUE THREAD

**Issue by cfarence** [calzoneman/sync#542]
I'm getting a redirect loop when trying to access anything on /account Everything else works fine /r/CHANNEL_NAME /acp but for some reason I get 302 redirect on /account 

I do have nginx sitting in front of sync preforming ssl termination and it proxies it to localhost:8080. The proxy does set the x-forwarded-proto header. I'm not sure why its 302 redirecting /account/ I can't find any error in the logs, and nginx access log doesn't really tell me much either. Everything else works fine web sockets are on the default port working fine with ssl enabled.

**Comment by calzoneman** [comment]
Can you please post your nginx configuration for the proxy, and your config.yaml (with passwords redacted)?  You can also email them to cyzon@cytu.be if you don't want to post them publicly.

**Comment by cfarence** [comment]
Emailed

**Comment by calzoneman** [comment]
This is caused because `redirectHttps()` doesn't respect the `X-Forwarded-Proto` header (whereas the template engine does).  I didn't notice this because cytu.be has `https.redirect = false` (from https://github.com/calzoneman/sync/commit/813ae3a2ef85199c7a5ae0c83ce299d36c2d99c5, I can't remember why I did this).
