### ISSUE TITLE
Table creation query fails

### ISSUE THREAD

**Issue by henke37** [calzoneman/sync#543]
```
! DB query failed: CREATE TABLE IF NOT EXISTS `channel_libraries` (`id` VARCHAR(255) NOT NULL,`title` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL,`seconds` INT NOT NULL,`type` VARCHAR(2) NOT NULL,`meta` TEXT NOT NULL,`channel` VARCHAR(30) NOT NULL,PRIMARY KEY(`id`, `channel`), INDEX(`channel`, `title`)) CHARACTER SET utf8
{ [Error: ER_TOO_LONG_KEY: Specified key was too long; max key length is 1000 bytes]
  code: 'ER_TOO_LONG_KEY',
  errno: 1071,
  sqlState: '42000',
  index: 0 }
Database failure
```

I blame mysql for tying key lengths to the locale or something.

**Comment by calzoneman** [comment]
Which version of MySQL are you using?  It seems to work on MariaDB:

```
MariaDB [(none)]> use testdb;
Database changed
MariaDB [testdb]> CREATE TABLE IF NOT EXISTS `channel_libraries` (`id` VARCHAR(255) NOT NULL,`title` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL,`seconds` INT NOT NULL,`type` VARCHAR(2) NOT NULL,`meta` TEXT NOT NULL,`channel` VARCHAR(30) NOT NULL,PRIMARY KEY(`id`, `channel`), INDEX(`channel`, `title`)) CHARACTER SET utf8;
Query OK, 0 rows affected, 1 warning (0.24 sec)
```

But yes, MySQL's handling of UTF-8 is awful.  For now it should be fine to truncate the index, since the (`channel`, `title`) index is only used for library searching.  In the future I plan to abstract away the database interface to allow plugging in different RDBMSes (PostgreSQL, SQLite3 for small sites, etc.)

I'll commit a change to the table creation query, but to unblock yourself you can modify the query to this:

``` sql
CREATE TABLE IF NOT EXISTS `channel_libraries` (`id` VARCHAR(255) NOT NULL,`title` VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL,`seconds` INT NOT NULL,`type` VARCHAR(2) NOT NULL,`meta` TEXT NOT NULL,`channel` VARCHAR(30) NOT NULL,PRIMARY KEY(`id`, `channel`), INDEX(`channel`, `title`(227))) CHARACTER SET utf8;
```

The (227) specifies an index key length of 227 characters which works out to 908 bytes, add 90 bytes for the channel name part of the index (30 characters \* 3 bytes each since it's non-utf8mb4) and that works out to just under 1000 bytes.

**Comment by calzoneman** [comment]
And actually, `title` can probably be shortened anyways since the application logic should truncate titles to 100 characters or less (following an incident where someone crashed the server by adding a video with a 33,000 character title 2,000 times in the playlist).

**Comment by henke37** [comment]
```
Värd: localhost3306
Databas:
Skapad: 16 dec 2015 kl 07:41
Genererad av: phpMyAdmin 4.0.10.7 / MySQL 5.5.46-cll
SQL-fråga: SHOW VARIABLES LIKE "%version%";
Rader: 7
Variable_name   Value   
innodb_version  5.5.46
protocol_version    10
slave_type_conversions  
version     5.5.46-cll
version_comment     MySQL Community Server (GPL)
version_compile_machine     i686
version_compile_os  Linux
```
