### ISSUE TITLE
(Multiple users, replicable) Switching layouts causes playlist to disappear.

### ISSUE THREAD

**Issue by programnoir** [calzoneman/sync#549]
A friend and I are using computers of multiple resolutions. Selecting Options > Layout and switching layouts sometimes causes the playlist section of a channel to disappear, namely, the HD -> Fluid + Synchtube (Flipped) option. Pressing CTRL+F5 resets everything and clears that up. Interesting bug.

**Comment by calzoneman** [comment]
Originally I didn't support changing back from HD layout without refreshing at all, since alternate layouts are just javascript functions that run on page load and rearrange the elements on the page and the HD one in particular wrecks the original layout.

A function for switching back to compact from HD was proposed and added in #336 but I guess I never did the same for the other layout types.  The reason F5 resets it is that the layout functions all start from the default layout as a base and then modify it, whereas before refreshing it's trying to go from HD to flipped and that doesn't work.

**Comment by calzoneman** [comment]
This is fixed by https://github.com/calzoneman/sync/commit/865a7453d9e742babffbe4013279ab3b19241b24.  You can test it out on http://beta.synchtube.me and I'll be rolling it out to cytu.be later this week.
