### ISSUE TITLE
Ability to rename emotes

### ISSUE THREAD

**Issue by xkaype** [calzoneman/sync#557]
Hello,

I was wondering if in the future there could possibly be an option to rename emotes,
similar to how you can modify chat filters.

Additionally, any plans for categorizing emotes in the future?

Thanks!

**Comment by calzoneman** [comment]
Being able to rename emotes wasn't in the original design because
1. It was assumed that renaming would be rare, and
2. You can just create a new emote with the new name and the same image

All it would require is a UI for doing that, but it's low priority.

As for categorizing emotes, that's something I would have to look into in the future since I didn't expect people would add enough emotes for it to become a problem.  Even if not an explicit category system, there at least needs to be pagination on the channel settings UI for it.

**Comment by xkaype** [comment]
> You can just create a new emote with the new name and the same image

When managing large amounts of emotes (our room has about 100 and counting) it can get kind of difficult to continue doing that.

However:

> Even if not an explicit category system, there at least needs to be pagination on the channel settings UI for it.

This would help a lot. Perhaps having previews of the emotes inside the channel settings wouldn't be a bad idea either, if you decide to go about this? I don't mean to nitpick, this is just something that randomly came up when me and a friend started renaming/replacing a few emotes that we had.

Thanks for the quick reply!

**Comment by henke37** [comment]
Try populating the add emote form when deleting an emote? That's convenient enough imnho.

**Comment by Xaekai** [comment]
I just export the list, go to the emote I want to rename, and rename it, and reimport.

I have ~1000 emotes in my channel and it's still relatively fast. I agree with Calvin, you shouldn't be this often enough for it to be a problem.

**Comment by calzoneman** [comment]
I've been planning to just replace the current emote editor with a modified version of the emote browser displayed to users in chat.
