### ISSUE TITLE
"Prevent chat flood" option

### ISSUE THREAD

**Issue by uchigawa** [calzoneman/sync#56]
What exactly this option does? I can't see any effect, I tested various channels on a few servers and it seems do not working.

Also, I got strange messages in a chatbox:
`requestAcl: Stop doing that so fast! Cooldown: 5s`
after fast clicking `Channel Ranks` tab. No effects after clicking other tabs.

It happens on your server too. And after reloading this option is always unchecked.

**Comment by calzoneman** [comment]
When "prevent chat flood" is checked, clients will be throttled in the number of chat messages they send.  If they send too many too quickly, the server responds with a warning and stops transmitting messages from that client for 5 seconds.

A similar thing is happening with requestAcl.  Because loading the channel ranks tab requires hitting the database, I've throttled it to prevent a DoS attack by flooding the server with requestAcl packets.

I'll look into the unchecking issue.

**Comment by calzoneman** [comment]
It appears that somewhere in the course of my development, the anti-chatflood feature I implemented never actually got committed.  It was only a few lines, so I'll go ahead and add it back
