### ISSUE TITLE
Keep playlist running with no users

### ISSUE THREAD

**Issue by mvh6** [calzoneman/sync#578]
Is there any way to keep the playlist running without anyone in the room. This would be highly effective for me as an European with a mostly American audience. As i usually stream during European night, i want to have a replay of my playlist stream at night American time. I figured i could do this by scheduling random videos until the time i wanted my video to stream for my audience. I can't do that currently as when there's no ones in the room, the playlist stops playing. Is there any way to work around this? That would be awesome!

**Comment by calzoneman** [comment]
Channels are saved and unloaded from memory when there are no users in order to save server resources for non-idle channels.  Some people keep their channel open by always having a bot join it, but I discourage doing it because it's wasting memory and CPU time for a channel no one is using during that time period.

I wonder whether it might make sense for you to just add your video to the playlist and then leave for the night, then it would start as soon as people show up in the morning?  That seems more flexible than trying to schedule things to start at a certain time without being there.  CyTube wasn't really built for scheduled content.
