### ISSUE TITLE
Twitter support?

### ISSUE THREAD

**Issue by cobrafast** [calzoneman/sync#584]
Can we get support for Twitter videos?

Right now we can neither add the post link nor the video link (since it doesn't end on any of the supported file extensions).

**Comment by calzoneman** [comment]
This is probably possible, albeit kind of annoying because they use OAuth

**Comment by Xaekai** [comment]
Twitter is indeed annoying, and not because of OAuth.

Having added Twitter support to PonkBot, I can tell you right now it will be a source of frustration for users because some tweets with videos return a nice set of direct video links and others return just another link and there is no clear distinction between the two in their UI.

The API call
https://dev.twitter.com/rest/reference/get/statuses/show/%3Aid

Normal one
https://twitter.com/katiemoffat/status/567972190639022080

Example of iframe'd / no direct links
https://twitter.com/PrisonPlanet/status/746451109657513984

The JSON response will only give you yet another URL for that: https://amp.twimg.com/v/1bd4f5e1-c57d-4dde-b201-3961276e6fdb Which appears to be an iframe wrapper for something they call Amplify.

I suppose you could just handle that like you do YouTube I guess. I'm mostly just frustrated because the documentation on these latter kinds of tweets is sparse to non-existent.

**Comment by calzoneman** [comment]
Closing since I don't plan to add this, for the reasons Xaekai mentioned above.
