### ISSUE TITLE
Streamable.com support?

### ISSUE THREAD

**Issue by cobrafast** [calzoneman/sync#585]
Can we get streamable.com support?

Adding the post-URL doesn't work, but adding the video-URL does.

**Comment by calzoneman** [comment]
I took a look at their API and it seems reasonable, but does not include the duration of the video in the response, which is one of the metadata fields CyTube needs.  I've reached out to them via email to ask if this can be added, and if it is then I'll be willing to support streamable.

**Comment by photonman62** [comment]
As a workaround, Streamable has direct links to the videos. Right-click the video, click "copy video URL" and you can use that as a synchtu.be link. It doesn't show a title this way, but you can use it for individual videos you want to show on your channel.

**Comment by calzoneman** [comment]
"Adding the post-URL doesn't work, but adding the video-URL does." -- the person who filed this issue was already aware of this workaround, but it's not ideal for several reasons:
- More effort for the person adding the video
- Wastes resources on both CyTube and streamable.com since CyTube has to partially download the file in order to extract the metadata rather than just querying a short JSON endpoint
- Slower because of the above
- Doesn't support multiple quality levels (believe it or not, there are people using CyTube on connections or devices that can't handle a 720p video)

So yes, it is technically possible to use streamable.com videos right now, but if I can hear back from them about including the duration in the JSON API, I'd rather add full support for it.

**Comment by calzoneman** [comment]
Haven't heard back from them yet, will re-send my email.

**Comment by calzoneman** [comment]
Email thread quoted below.  If I still don't get a response I'll ping the thread again.

Hi,

To give some context, I run a website that allows users to embed videos from various websites and synchronize them so that everyone is watching at the same time.  One user requested streamable support via this GitHub Issue: https://github.com/calzoneman/sync/issues/585.  In order to set the synchronization timer, as well as display stats such as the total duration of the playlist for a channel, it's necessary for the backend to know how long each video is.

Hopefully this makes the request more clear.

Thanks,
Calvin

**Comment by lawlmart** [comment]
Duration is now included in the files portion of the API response. 

Usual caveats apply - this is not publicly documented and therefore subject to change.

**Comment by Xaekai** [comment]
That is awesome news.

**Comment by calzoneman** [comment]
Metadata query implemented: https://github.com/CyTube/mediaquery/pull/5

**Comment by calzoneman** [comment]
This is now merged, so closing the issue.  It will be included the next time cytu.be is deployed.
