### ISSUE TITLE
Googlevideo support?

### ISSUE THREAD

**Issue by cobrafast** [calzoneman/sync#586]
Can we get googlevideo.com support?

Adding a googlevideo.com direct video URL (à la https://...googlevideo.com/videoplayback?id=...) results in 

> The file you are attempting to queue does not match the supported file extensions mp4, flv, webm, ogg, ogv, mp3, mov.

[Example](https://r13---sn-ab5l6ned.googlevideo.com/videoplayback?requiressl=yes&id=7a217760669e327b&itag=22&source=webdrive&ttl=transient&app=texmex&ip=45.63.14.76&ipbits=32&expire=1467077487&sparams=expire,id,ip,ipbits,itag,mm,mn,ms,mv,nh,pl,requiressl,source,ttl&signature=2ADF7798AFCACF9FB31C3926F9F210741E78770C.1E4C8BC4DC6ADAF364F797338AF88052A9BD8CCA&key=cms1&pl=21&cms_redirect=yes&mm=31&mn=sn-ab5l6ned&ms=au&mt=1467075241&mv=m&nh=IgpwcjA2LmxnYTA3KgkxMjcuMC4wLjE)

**Comment by calzoneman** [comment]
1. Usually, googlevideo.com links will not work, because they contain a signature to ensure that only your IP address can access the video (which means CyTube wouldn't be able to query it), and an expiration timestamp that means the link no longer works after 1 hour.
2. If you're sure that the link you have will work, you can override the UI link detection by prefixing the link with `fi:`, e.g. `fi:https://...`.  The link will still be verified by the server, which will return an error if it is unable to query the video.  This is a limitation of the current UI for detecting link types, which was intended for people who operate their own webservers and not random links scraped from the internet.
3. Google Drive and Google+ videos are supported natively without needing to copy and paste such links.  See the [wiki](https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#which-media-providers-are-supported).
