### ISSUE TITLE
Add Kisscartoon/Kissanime Support

### ISSUE THREAD

**Issue by SirShiggyDiggy** [calzoneman/sync#608]
Would it be possible to add Kisscartoon and Kissanime support?

**Comment by Xaekai** [comment]
No. It is not possible. This was discussed on the [CyTube blog](http://blog.cytu.be/). KissCartoon piggybacks off of Google Drive/Google Photos for their actual content hosting. Google binds retrieved metadata to specific IPs. Although there is a work around, it is quite hacky and requires the retrieving host to have two IPs. In addition to this, KissCartoon has gone to great lengths to obfuscate their source links on their pages and since they are running such a sketchy service they currently offer no API and almost certainly will never add one.

**Comment by calzoneman** [comment]
To give you an idea, the actual video links on the kisscartoon page are encrypted with AES and the JavaScript functionality to decode them is very heavily obfuscated. Even if I spent the time to reverse engineer that, I'd have to find a way to bypass Cloudflare's browser/bot detection in order for the server to get the links.
