### ISSUE TITLE
vk.com support?

### ISSUE THREAD

**Issue by 165your4** [calzoneman/sync#619]
I was wondering if support for VK videos would be possible. Much like Dailymotion, the site is great for videos that would be taken down on other sites due to copyright infringement.

VK API: https://vk.com/pages?oid=-17680044&p=VK_API_Documentation

**Comment by calzoneman** [comment]
Is there content on VK that is not explicitly for the purpose of copyright infringement?  I'd rather not turn the site into a honeypot for copyright infringing videos, that would reflect poorly on me legally.

**Comment by 165your4** [comment]
Well, its actual purpose is a Russian version of Facebook, so yes. Outside of Russia its known more for movies/TV shows, but that's simply a consequence of its less strict copyright rules, not an intentional feature as far as I can tell.

**Comment by calzoneman** [comment]
The API page you linked seems to be mostly about the generic data API of VK, not about the video player (after all, it is more of a facebook than a video site).  I did some digging around and I did not find anything suggesting they support a video playback API, only embed codes (which are not syncable).

So I'm closing this for now, if you find information to the contrary feel free to share it.

**Comment by RblSb** [comment]
@calzoneman whether it is possible to make customers get the video stream via the link from the site? Then work with him via videoElement.currentTime. 
https://vk.com/dev/video.get

It is necessary to parse links like:
https://vk.com/videos-23478453?z=video-23478453_159151612
To get '-23478453,-23478453_159151612' to 'videos' parameter.
This is enough for the method, it will return a list of links to video files that are linked to the user's ip.

**Comment by calzoneman** [comment]
Requiring each client to request its own link tied to an IP is infeasible, because it requires installing a userscript to bypass CORS policy.  I had to do this for Google Drive, it's hacky, and the only reason I did it for Drive was to preserve an existing video provider.  I would not consider it for a new source.

At this time I do not intend to support videos from vk.com.  The currently supported list of providers is available [on the FAQ](https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#which-media-providers-are-supported), and I am willing to consider adding other, legitimate video providers with appropriate data and embed APIs.

**Comment by RblSb** [comment]
@calzoneman okay, thanks for explanations. Another question is whether it is possible to transfer the time of your iframe video player to other members of the room? With the help of cytube channel script (get/set time function of the external player) and patching cytu.be/callbacks.js.

That would be very cool, because most video hostings does not give the video without reference to the ip.

**Comment by calzoneman** [comment]
No, this is what I mean by "embed API", which vk does not have.  Browsers essentially treat `<iframe>` embeds as a separate page, so it is not possible to directly cross this boundary due to security policy.  Websites like YouTube provide an API via [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) that allows JavaScript on the source page to communicate with JavaScript running inside the frame.  Without this, it is not possible to have any control over the content in the `<iframe>`.

**Comment by RblSb** [comment]
@calzoneman Oh, I am very retarded :D
In such a case, it may be done using extension to the browser? This could be a big step in the development cytube, bypassing all these restrictions.

**Comment by calzoneman** [comment]
I don't know if it would be possible with a browser extension, but even if it were, I would not be interested in supporting that.  Google Drive support was an experiment in supporting a video source that did not have a documented API, and the result has been that maintaining it has been a significant waste of time and effort as well as causing pain to users every time it breaks.  I think I've probably spent more time trying to keep Google Drive working than adding support for every other video source combined.  This has led me to make the decision that from now on, I will only consider adding support for video sources that have an officially supported and documented embed player API.

In practice, every video site worth a grain of salt has a playback API, and most sites that do not support this are either sketchy filebin sites and/or sites that people only want to use with the explicit purpose of bypassing copyright restrictions.  I have no interest in maintaining some janky duct-taped setup for such websites which will only create more work for me and increased likelihood of DMCA and other legal notices due to users who violate the terms of service by illegally sharing content.  The existing supported websites cover a wide range of legitimate use cases.

**Comment by RblSb** [comment]
@calzoneman Very sorry. So you can not help me if I decide to do by adding support iframe-players through patching cytube scripts?

**Comment by calzoneman** [comment]
There's no need to be sorry, I'm just explaining the reasons why I won't support it.

> So you can not help me if I decide to do by adding support iframe-players through patching cytube scripts?

Unfortunately, no.
