### ISSUE TITLE
Bugs in Options' layout switcher

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#62]
It's impossible to revert to default layout after changing to any layout from the list, it's necessary to clear cookies to bring back default one. Also, SynchTube layout is not present. (using latest Chrome, dunno about Firefox)

**Comment by calzoneman** [comment]
You have to refresh after switching back to default layout.  I was considering adding an auto-refresh because all of the layout switches are meant to start from default, but I figured that would be obnoxious.

I removed synchtube layout temporarily because I didn't know anyone actually used it and I need to fix it from my default layout change.  The button's still there in the meantime.

**Comment by calzoneman** [comment]
I added a disclaimer to the options box to make it more clear that refreshing will fix a broken layout change.

Fixed the synchtube layout, I just wasn't thinking about it when I initially did this because I never use it.

**Comment by ghost** [comment]
Our biggest room is using Synchtube Layout as default via custom js :D
(PS. Could you put your BTC wallet address in the footer?)

**Comment by calzoneman** [comment]
I should have thought about it, I just didn't.  Also, to avoid further confusion, the "Narrow Layout" was deprecated in favour of "Single Column".

I don't have a BTC wallet at the moment.  I have a PayPal, but their donation system is a bit annoying to donors (in my opinion), and for small amounts the transaction fee ends up costing half the donation.  If I set up bitcoin, I'll add it to the footer.
