### ISSUE TITLE
Adding webtorrent support. Need information on how to navigate code

### ISSUE THREAD

**Issue by PabloDons** [calzoneman/sync#629]
This is not a bug, therefore I won't follow the format given. I just want to know how to navigate the code. Instead of spending hours (maybe days because I get lost easily), I decided to ask.

basically, I am planning on integrating this: https://github.com/feross/webtorrent
Essentially, it will allow users to enter either a magnet link or a download link for a .torrent file and it will allow users to stream torrents without any middle man. This will impair users in restricted network connections from watching, but there's always the option of using a VPN which proxies all the traffic through a single port.

Here's what I need:
1. Where does the media type detection happen?
2. Where is the video frame created in the browser?
3. Where is the video frame synced in the browser?
4. Where is a raw-file video frame created in the browser?

Thanks in advance. Rant incoming.
I am writing this new video format because we have a community theater that we run movies on every Saturday. We end up torrenting movies and uploading them to gdrive a couple of days before Saturday, which has become kind of a pain. This will simplify things a lot as all we'll need to is paste a magnet link. It'll be quite a challenge because I've never worked with nodejs before, but I've worked actively with javascript, so I think I will manage. unless of course you'll want to do it yourself. In which case I'd like to know so not to waste a huge amount of time. Anyways this will most likely be very useful for a bunch of people other than me as well. Will make for much more interesting channels.

**Comment by calzoneman** [comment]
I think there are some technical issues with your suggestion:
1. The torrent protocol does not lend itself well to playing content while you're downloading it.  Files aren't downloaded synchronously like with HTTP; rather, the chunks of the file are downloaded out of order, based on availability from peers.
2. Attempting to synchronize a few dozen clients to all download the file sequentially at the same time, assuming (1) can be solved programmatically, seems like it would create a bottleneck by introducing a bunch of leechers all at once.  Since playback is realtime, you can't really count on some viewers to re-seed a chunk to the other clients; by the time they download it and seed it to peers, that part of the video is already over and clients are trying to get the next chunk.
3. Based on (1), it could be difficult for the server to look up the metadata without torrenting the entire file (or a sizeable chunk of it).  I'm assuming that you would have to download it and re-use the existing `ffprobe` code to extract metadata.

Basically, I imagine this would actually perform worse than simply asking users to pre-download a video and just use the synchronization timer with local playback.  However, you are welcome to create your own fork and attempt to implement this for yourself.  You can refer to [this](https://github.com/calzoneman/sync/pull/606/files) and [this](https://github.com/CyTube/mediaquery/pull/5/files) PR for the work I did to support streamable.com; that should give you an idea of where to look when adding a new video source.

Lastly, I probably wouldn't want to support this in core / on the live site due to legal concerns.  Whether or not it's technically legal, I'd rather not pick that fight.  I'm content to allow users to share links to files hosted by 3rd parties, and remove such links whenever I receive a DMCA takedown notice.

**Comment by PabloDons** [comment]
Thanks for the reply, your concerns are completely valid and there's been quite a lot of effort put in to solve those problems.
1. This problem was (somewhat) solved by a program called peerflix. It takes in a torrent and streams the content either to a player or a file. In the bittorrent protocol you can requests certain chunks by their index. I'm not quite sure how peerflix does it, but they probably figure out which clients have certain chunks and connects accordingly in order to download as synchronous as possible. I assume the metadata is at the beginning of the file too. Unfortunately this isn't perfect and takes a short while for the video to start up. Webtorrent is based on this. I don't know how well it will work with a script constantly trying to skip the video to sync it, but I think the first few moments will be annoying until it finally downloads an amount it can work with.
2. That mostly applies to clients with bad connection. Most of the time, the download will finish before the end of the video. Even if it doesn't, someone with a really good connection will have downloaded a large portion of the video already and leechers will choose that as the client. When it comes to the question whether clients will seed back is also solved with an incentive system. If there is a client that doesn't send the data it has that you're requesting to your client, you'll be less likely to seed to it. Essentially, the download speed of a client will slow significantly if it doesn't seed.
3. Not at all, the metadata is usually completely downloaded within the first few seconds. Again, I have no idea how streaming with torrents works, but you'd be surprised.
4. You mentioned legal issues. Unfortunately there is no way I can answer that because I am no law student, but consider this; how exactly does DMCA strikers figure out if your site is serving a copyrighted movie? Through downloading the source and checking, right?  What if there is no source to download from? The video is a blob after all. Copyright  enforcement is usually done automatically and I doubt they are using torrent software. Of of course, they might, but how would they know what torrent is used? It is just a JavaScript variable after all. Either way, you can't really connect directly to the bittorrent network because of security measures done by the browser, so you'll have to seed it yourself first. It's not much different from uploading a file to a personal server and hosting it yourself in that situation. But with torrents, you won't need to know anything about hosting to do it, and the load will be significantly smaller.

Anyways, thanks for the links. I'll check it out. Hopefully you can consider letting people use torrents on the official site. I could host my own clone of the site since your licence allows it, but I'd rather not, I'm no master web host myself.

**Comment by calzoneman** [comment]
I suppose the technical feasibility or infeasibility won't be clear until you try it.

With respect to the legality:
- Thus far, all DCMA takedown notices I have received have been manual, not automated.  Someone discovered a channel via their advertisements in other places (e.g. reddit, imageboards) and reported the copyrighted content to my email address from the Contact page.  What is being used to serve the copyrighted content is not relevant in this case; they have legal precedent to send a takedown notice.
- Again, it's more of an issue of "that's a grey area I'd rather not enter" than a straight up "this is illegal".  At least the other content providers I support have plenty of legitimate content; I think it'd be a tough sell to claim webtorrent support will be used for anything but blatant copyright infringement.
- Due to the nature of torrents, this potentially puts viewers at risk as well.  While downloading copyrighted content, e.g. watching a film someone uploaded to YouTube, is typically not pursued, seeding copyrighted content to other users is considered copyright infringement and is pursued by US ISPs (https://en.wikipedia.org/wiki/Copyright_Alert_System).
