### ISSUE TITLE
Show (empty) channels in public list

### ISSUE THREAD

**Issue by fibasile** [calzoneman/sync#630]
I would like to keep all the channels created visible even if they are empty. Is this possible without using an external bot? In alternative, where could I find the query filtering empty channels?

**Comment by calzoneman** [comment]
The channel index is not querying the database, it is listing the channels loaded in memory.  In order to save resources, channels that are empty are unloaded from memory, and hence do not appear in the index.

If you are running your own copy of the software, you can remove [the empty channel unload logic](https://github.com/calzoneman/sync/blob/3.0/src/server.js#L216-L218), at the expense of keeping empty channels in memory.  Alternatively, you could implement an indexer that queries the database for known channels, but I don't have an example of this.

If you are using an existing website, there is no option but to keep a user in the channel so it stays loaded.
