### ISSUE TITLE
Google Drive - userscript not working for one user

### ISSUE THREAD

**Issue by Shiyounin** [calzoneman/sync#634]
Hello devs,
As the title says, your Google Drive userscript doesn't work for one of my users.
This is what he gets when he joins a channel playing a Google Drive video: "The media could not be loaded either because the server or network failed or because the format is not supported".
Please notice that the said channel is not self hosted.

Since it works great for everyone else I assume this is some sort of client-side issue, and I'm pretty sure it's not directly caused by Cytube itself... 
However, I hope you guys will be kind enough to help us out anyway. Here's some information about the said user you might find useful:
- he's using Tampermonkey on win10 (as I do), and he installed the userscript on both Chrome an Firefox, not to mention Edge. He even tried this on a different device (notebook) and it's still not working. It almost looks like the script doesn't even load when he joins the channel.
- he can access and view the same failing video on Google Drive if provided the link;
- I asked him to type "window.hasDriveUserscript" on his browser console, which resulted in this response: "undefined". 

If you need some extra-test, please ask me freely.
I thank you in advance for your support.

**Comment by calzoneman** [comment]
Hi,

First of all, thanks for the detailed description of the problem and what you've tried already, that's helpful.

If `window.hasDriveUserscript` is not returning `true`, then the script is not running, either because it is not installed properly or it is not running properly.  The console will also show `Initialized userscript Google Drive player` when the script is loaded.  Below shows what Tampermonkey should show when the script is properly installed:

![2016-11-17-202038_1916x1044_scrot](https://cloud.githubusercontent.com/assets/385672/20418568/b8994638-ad03-11e6-9f29-6439823fb5b4.png)

If this is not the case, make sure:
- You are connecting via `cytu.be` or `www.cytu.be` &mdash; alternate addresses are not supported by the script.
- The script is actually installed (check the Tampermonkey dashboard) &mdash; just opening the userscript link will go to a confirmation page but not actually install the script; Tampermonkey requires you to accept the installation.

When the script is not running, you should also still see the prompt explaining that it needs to be installed below the video.

If the script is running but the video still doesn't play, make sure you have enabled 3rd-party cookies as this is required for Google Drive:

![2016-10-29-193649_669x636_scrot](https://cloud.githubusercontent.com/assets/385672/20418600/24939f32-ad04-11e6-9de7-984a18c818e2.png)

The person having the problem can join [IRC](https://webchat.6irc.net/?channels=cytube) for further help, as GitHub issues are typically used for bugs and features about the project rather than troubleshooting individual users' problems.  IRC allows for quicker communication as long as someone is available to answer the question (typically between 6pm and midnight Pacific time).

**Comment by calzoneman** [comment]
I haven't heard back so I'm going to close this out since it seems to be an individual issue and not an underlying problem with the project.  Feel free to reach out via IRC or email for further questions.
