### ISSUE TITLE
Enforcing HTTPS

### ISSUE THREAD

**Issue by RblSb** [calzoneman/sync#638]
Can you explain that for which I have to fuck a few hours with https certificates? The site is have https support for dumb browsers and their owners, who are concerned about safety, so why endure http?
And, of course, as I can now to stream from the local network?

**Comment by RblSb** [comment]
I would also appreciate it if you specify the commit (or something), who made it a wonderful change.

**Comment by SysadminJeroen** [comment]
#636 

I recommend using Let's Encrypt. You won't have to play with certificates for hours if you use Let's Encrypt.
Embrace the steps towards an encrypted and secure internet.

**Comment by SysadminJeroen** [comment]
The specific commits:

453ed607badc8ae5596e44710e694eb484ba05b8

53d385f53e3b7afc358654dc7326254f0718d7ff

8719527a313a406b56ca3c6d2e03adfe4d55de41

Here is the patch file that did the change. https://patch-diff.githubusercontent.com/raw/calzoneman/sync/pull/636.patch

**Comment by RblSb** [comment]
@Jeroen52 but I cant use Let's Encrypt in my public ip, right?

**Comment by calzoneman** [comment]
>Can you explain that for which I have to fuck a few hours with https certificates?

The reason to force all content to be HTTPS is not due to concerns about the content itself, but due to mixed-content policy with the site (https://cytu.be) becoming HTTPS only.  A page accessed over HTTPS cannot load videos over plain HTTP; browsers block this.

Plain HTTP only affects raw file links, and accounts for just 1% of all content played on the main site.  It is not justifiable to hold back progress on the entire site just to continue supporting this legacy use case.

>The site is have https support for dumb browsers and their owners, who are concerned about safety, so why endure http?

You may think it is dumb, but the reality is that the internet is migrating off of plain HTTP to HTTPS.  Chromium is already [announcing plans](https://blog.chromium.org/2016/12/chrome-56-beta-not-secure-warning-web.html) to eventually have Chromium explicitly warn users about plain HTTP websites.

If you are hosting your own server, you are welcome to revert the HTTPS related patches and continue using plain HTTP.  However, I do not provide upstream support for this anymore.

Commits for enforcing HTTPS for video content (due to mixed-content policy):

  * https://github.com/calzoneman/sync/commit/e2abb90d1418baddee3e4a1f9710f1e49391a74c
  * https://github.com/calzoneman/sync/commit/e1ad7c63aff557e7a707a77d34944f08c52d82aa

You could also just look under https://github.com/calzoneman/sync/commits/3.0, I usually try to give descriptive commit messages.

>but I cant use Let's Encrypt in my public ip, right?

HTTPS certificates require a domain name, they don't work with a plain IP address.  However, there are plenty of places you can get a free subdomain, such as [FreeDNS](http://freedns.afraid.org/).

**Comment by justjanne** [comment]
@RblSb: to continue streaming from the local network, you can get an HTTPS certificate for a domain, and afterwards change its DNS records to point to a local IP. This model is used by Plex for the very same purpose.
