### ISSUE TITLE
Can't delete my channel

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#653]
I can't delete my channel even though it's listed on "my channels". I'm rank 5 on it, there is nobody else with a mod, but the thing is one character of my name is uppercased and differs from my registered name.

There was a time when you could login using uppercased/lowercased variation of name, like "user" -> "UsEr", and be seen as such on channels, but it's no longer possible, I guess that's the case.

![1](https://cloud.githubusercontent.com/assets/13720588/24169826/0fa2a064-0e7f-11e7-992b-e3f26da7fd03.png)
![2](https://cloud.githubusercontent.com/assets/13720588/24169827/0fa3430c-0e7f-11e7-93d6-cf18837fe4d9.png)

**Comment by calzoneman** [comment]
Most places on the website, usernames are case-insensitive, but this is one place where apparently it's not.  I'll work on fixing it, but in the meantime if you would like to delete a channel, please let me know the name and I'll remove it manually.

**Comment by Xaekai** [comment]
I'm rather shocked this issue took this long to surface

**Comment by calzoneman** [comment]
People don't delete channels often, and as mentioned in the issue overview, the time period where you were allowed to log in using a different casing of your name was a long time ago (you can still use any case when logging in, but the resulting login will have the case matching what's in the database).  So triggering it has a very low probability because you need to be both (1) deleting a channel (rare), and (2) have created the channel while logged in with a different capitalization (rare).

**Comment by calzoneman** [comment]
As it so happens, I deployed the fix for this tonight, so you should be able to delete your channels now.
