### ISSUE TITLE
Whitelist for channel javascripts

### ISSUE THREAD

**Issue by henke37** [calzoneman/sync#658]
A whitelist of channel javascripts that does not require authorization by the visitor.

**Comment by calzoneman** [comment]
I'm not interested in allowing whitelisted channel JS at the moment:

  * Embedding scripts without the user's consent provides an implicit assumption that the website endorses the script.  The current prompt method makes it clear that the website owner does not endorse the channel's custom content, and that the user is opting-in to an altered experience.
  * I strongly believe that users should not load custom JS by default.  It should be an opt-in, not opt-out, experience.  My guideline for channel JS is that it should only provide additional features on top of the core that users may wish to opt-in to enjoy; it should not make the channel unusable or have a degraded experience without the JS running.
  * There is minimal convenience to adding this feature.  The user already has the ability to select "Remember my decision", and the website will keep track of which channels are authorized to run channel JS without prompting the user each time.

I have, in the past, considered having some sort of whitelist or "marketplace" that channels can choose approved scripts from, although it would still require users to opt-in due to the reasons above.  One reason I haven't looked into this is because I don't currently have the time or interest to review every update to every script, but there may be other advantages to doing it that way.

Overall, channel JS currently is treated more like a convenience for userscripts rather than an officially supported API for customizing the user experience.
