### ISSUE TITLE
Windows is explicitly not supported

### ISSUE THREAD

**Issue by refriedfood** [calzoneman/sync#723]
That's a bug. I'm willing to help pay to have it removed from the devs ass.

**Comment by Xaekai** [comment]
Are you also willing to pay for the flood of nuisance techsupport we would have to field from the masses of unqualified wannabes? The lack of Windows support makes for very useful barrier to entry to weed out needless time sinks.

**Comment by refriedfood** [comment]
"nuisance techsupport" I'm sorry, are you getting paid? Did you ever hear of a site called Veetle which was doing what this is years before it was probably even thought of? The only difference they had was they were client/web based with a VLC backend, and allowed for more sources and rtmp that way, not to mention the front part of the site that made it seem as though they were nothing more than just another hack youtube site for cell-to-video submissions, but it was all bullshit and apart from the real site. Cytu has no front, no protection, and I hardly see how supporting winOS hinders anything that isn't already glaringly vulnerable.

**Comment by calzoneman** [comment]
I'll start by answering the original question:

You're referring to the bolded sentence on the [installation guide](https://github.com/calzoneman/sync/wiki/CyTube-3.0-Installation-Guide), is that correct?  To be clear: this is referring *specifically to the node.js server software*.  The website itself of course works on Windows, since it does not depend on any OS-specific browser features.

Originally, I kept the same stance that I had for OS X and Solaris, which was "it might work, I don't have a way to test it but if you find a specific bug for this OS and submit a PR I'm willing to accept it" ([example](https://github.com/calzoneman/cytubefilters/pull/1)).

At some point recently, there was a person trying to run this server software on their Windows machine and ran into some issues, probably with one or more of the C++ bindings from node.js to various software libraries that CyTube uses, so the note was added that I don't support Windows.

I don't even recall what the issue is, if someone really wants to fix it more power to them, but I personally do not find software development and/or server administration on Windows to be something that I'd want to do, not to mention the extensive licensing fees just to operate a copy of the operating system.

**Comment by calzoneman** [comment]
>"nuisance techsupport" I'm sorry, are you getting paid? 

No, we're not.  What Xaekai is referring to is not the general case of helping end-users, but the times that a lot of time is spent painstakingly walking someone who knows nothing about server administration through setting up a server when there are hundreds of guides about setting up e.g. MySQL already available on the internet.  I don't think he was referring to you, or implying that this ticket is a nuisance.

>Did you ever hear of a site called Veetle which was doing what this is years before it was probably even thought of?

I have not heard of that particular one, but I don't claim that what I'm doing here is unique.  The very genesis of this project was my idea to recreate synchtube (which is now defunct) to learn about the technologies they were using.  After synchtube shut down permanently in 2013, this site gained unexpected popularity.

>Cytu has no front, no protection, and I hardly see how supporting winOS hinders anything

There are a couple ways to respond to this:

  1. I do not develop on Windows, nor do I have any desire to learn how to do so.  This project was and continues to be a hobby, not a job, so I generally don't spend time working on things that I don't want to do.
  2. Even if someone else contributes the code, it is still code that has to be maintained.  It will break, need updating, etc.  Contributing code is not as simple as just dumping it and leaving, it requires a commitment.

>that isn't already glaringly vulnerable.

If you have any specific security issue you'd like to discuss, please take it to email (cyzon@cytu.be); let's not discuss any potential compromising security flaws on the public GitHub tracker.

General comment: whether or not you disagree with the commenter above you, I would advise not going on an angry rant about the software if you're trying to get useful support out of a GitHub ticket.

**Comment by calzoneman** [comment]
I have updated the documentation and replaced the OS compatibility paragraph with a table clarifying the level of support:

https://github.com/calzoneman/sync/wiki/CyTube-3.0-Installation-Guide#operating-system

Please note the statement about Windows support was never intended to be derogatory; it was simply intended to save the user the trouble of installing everything only to discover it didn't work, given that I already knew the software was incompatible with Windows.

Let me know if there are further questions, or if you would like to assist with troubleshooting why it doesn't work on Windows.  I don't have an installation handy, and unfortunately I lost the chat logs from the time when I originally added that statement to the wiki.
