### ISSUE TITLE
Autoplay issues

### ISSUE THREAD

**Issue by ryulong** [calzoneman/sync#754]
YouTube Videos in the playlist on the website do not automatically play after one video is complete. I was hosting a room to play a couple of videos and when the first video finished, the next video would not load into the video player and begin playing the next video. When manually removed the video the next video would open in the player but it would pause and not play. I was hosting the room at this time, and the other user told me it was acting the same for him with a different computer entirely. I have not changed any custom settings for the channel. I was hosting a room about 2 weeks ago and did not encounter any issues and I have not made any major changes to my browser since then.

**Comment by calzoneman** [comment]
Can you confirm whether by "hosting the room", you mean that you clicked your name, clicked "Give Leader", and thus had a star icon next to your name?  Or do you just mean that you owned the channel in question?

Can you also confirm that "on the website" refers to https://cytu.be and not any of the other websites which operate using the same software?

Is there any way you could contact me privately to provide the room name so that I can investigate further?  See https://cytu.be/contact.

**Comment by ryulong** [comment]
I owned the channel in question and I was on synchtu.be and not cytu.be. Synchtu.be has the same GitHub links to this project.

**Comment by calzoneman** [comment]
I'm unable to reproduce the issue.  I'm not the owner of synchtu.be so I don't know for sure whether they are using the latest version of the code or there are any issues specific to that site, and I don't have access to their logs to see if there's some problem I don't know about.

**Comment by ryulong** [comment]
I will probably use cytu.be from now on so I guess this is sort of resolved. I could not reproduce the issue on cytu.be either.
