### ISSUE TITLE
Case sensitivity in email address impedes account recovery

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#755]
I had a user who could not recover their account after I gave them a hint about what email they used. When I investigated further, it seems they used the email `user@Domain.tld` instead of `user@domain.tld` when they first registered the account. This causes the account recovery dialog to report the email is not the one associated with the account.

Their are a few obvious ways to fix this, the first being to `.toLowerCase()` the user email input, the second being to make the database lookup case insensitive.

**Comment by henke37** [comment]
Note that it is up to each mail server if the account part of the address is case sensitive or not. The standard says that you should assume it is.

> The local-part of a mailbox MUST BE treated as case sensitive. Therefore, SMTP implementations MUST take care to preserve the case of mailbox local-parts.  In particular, for some hosts, the user "smith" is different from the user "Smith".  However, exploiting the case sensitivity of mailbox local-parts impedes interoperability and is discouraged.  Mailbox domains follow normal DNS rules and are hence not case sensitive.

**Comment by calzoneman** [comment]
What Xaekai is referring to is the matching of the username/email provided in the password reset form with that in the database, in which case comparing case-insensitively doesn't matter because one account can only have one email address.  That said, I don't think requiring the user to provide username + email address really adds any meaningful security and likely causes more problems than it solves (with people forgetting which email address they registered with).

If the user provides an email address which is not actually deliverable, that's a separate issue that is not an issue of string casing and would require some form of email address verification to prevent.

**Comment by Xaekai** [comment]
henke37 is saying throwing `.toLowerCase()` at the email field in handling the account registration form, which is indeed one of the solutions I suggested, would be a violation of RFC 5321. The `user` part of `user@company.tld` may be case sensitive in some email systems.

I humbly submit that such things are a unicorn, and I've only heard about such systems in legends. I suspect anyone *actually* using a mail system where mail sent to `johnsmith@company.tld` doesn't reach their `JohnSmith@company.tld` inbox would quickly be very very frustrated.

But it's easy enough to lowercase just the domain to be compliant.

**Comment by calzoneman** [comment]
I've added a case insensitive comparison to the password reset page.  I believe that resolves the issue without violating any RFCs.

**Comment by Xaekai** [comment]
Resolved via db2361a
