### ISSUE TITLE
expired certificate on https://synchtu.be/

### ISSUE THREAD

**Issue by arni2033** [calzoneman/sync#765]
1. Open https://synchtu.be/

Result: Firefox displays message "Warning: Potential Security Risk Ahead" w/o any way to override. Other browsers behave similarly.
Full text of the error on Firefox:
"Websites prove their identity via security certificates, which are valid for a set time period. The security certificate for synchtu.be appears to be expired.
Error code: SEC_ERROR_EXPIRED_CERTIFICATE"

It expired around 2018.08.17

https://synchtu.be/contact doesn't display any emails, so I'll just leave it here

**Comment by calzoneman** [comment]
I do not own or administrate synchtu.be. The owner disappeared and
unfortunately I have no means of contacting them about this issue.

**Comment by arni2033** [comment]
Oh, ok.
The footer on the site simply said "Copyright © 2013-2018 <your_name> <your_repository>"

**Comment by calzoneman** [comment]
The footer with the link to this repository is included by default since this is open source software that is used by many servers, and I want users to be able to discover where the software came from in case they would like to use it themselves, request a feature, etc.  However, you are right that it can be misleading about who owns the website.

**Comment by calzoneman** [comment]
It may be worth revisiting the footer text to indicate that the website *uses open source software from &lt;repo&gt;* to clarify ownership.

**Comment by ghost** [comment]
Fixed.
