### ISSUE TITLE
[Feature Request] Support for HLS VoD Streams

### ISSUE THREAD

**Issue by Tomoyochan** [calzoneman/sync#767]
I am working on improving local playback capability and HLS VoD works partly.  The player plays the files however there is no synchronization of the video feed.  A public HLS VoD feed is here that shows the issue: https://content.jwplatform.com/manifests/yp34SRmf.m3u8

**Comment by calzoneman** [comment]
Currently HLS support only targets livestreaming, for example in the custom media manifest format, it even verifies that HLS/DASH sources require `live:true`: https://github.com/calzoneman/sync/blob/3.0/src/custom-media.js#L32-L35.

I'd be curious to know what the value-add is of using HLS for prerecorded content instead of a static file (or set of files -- see https://github.com/calzoneman/sync/blob/3.0/docs/custom-media.md)

**Comment by Tomoyochan** [comment]
It seems the detection failed as I can play both VoD files and it thinks that they are live streams. 

As for the value add, It would provide two items.
1) Multiple resolutions so that bandwidth is not wasted on the sending server.
2) Low bandwidth clients can get a lower bitrate feed.  This is the main reason that I have setup a HLS VoD environment for testing as some viewers of the static files are unable to watch as the BW of the file is to high.  I do not want to drop the quality for all viewers however.

The player in use also seemlessly switches between the qualities ala youtube so if a users connection is temporarily slow it will drop down temporarily.

I will read through the custom-media document.

**Comment by calzoneman** [comment]
>It seems the detection failed as I can play both VoD files and it thinks that they are live streams.

To be clear: if you add an HLS file directly, it doesn't do any detection, it just assumes livestream (this predates the custom media manifest format).

Custom media manifests are intended to replace the self-hosted file support with a more advanced spec that allows users to define multiple formats/qualities for a single video as well as adding text tracks.

**Comment by calzoneman** [comment]
Also: the status says "Experimental", but I really should change that.  It's officially supported.

**Comment by Tomoyochan** [comment]
While functional the custom media manifest does not do things dynamically.

The users have to manually select the resolution they desire instead of the client choosing the best one for the conditions the way HLS does.   Further the client does not even default at the start to a quality that would be appropriate for the window size in my testing instead it chose the smallest one. 

To go back to why I would advise supporting HLS VoD:
1) It is a standard format used across a variety of services.
2) It is dynamic, youtube like setup, that adapts to the users window size and network quality automatically. 
3) From a viewer, non admin viewpoint, it is much more friendly and simple. All they have to do is watch and not manage the feed to be sure they have the best one for there needs.  This is important when you are talking 400+ viewers.  Trying to coach each one to the specific resolution they would need without having them choose the largest unnecessarily would be rather frustrating.
4)Most of the support is already there as the play back and skipping works when I add it directly.  I would only need to be able to synchronize the video feeds.   IF the system can not do it automatically, permitting the addition of the HLS VoD through the Custom Media Interface would work so that I can manually assign a duration.  I already attempted this and the system did fail out refusing to work as it is not live. 
This does seem to be a arbitrary limitation as the player itself and everything else about the system works fine with the VoD files.

**Comment by calzoneman** [comment]
Tagging this as available for pull request if someone wants to confirm this works and make the necessary modifications.  I don't really have a setup available to test HLS at the moment, and even if I resurrected my old HLS test setup, that only worked with livestreams and not vods.

For custom media, removing the assertion is sufficient for the server side; I don't know if any player changes are required.

For plain "add an m3u8 file", I don't know how you would detect the length because it's been a while since I read about the format.  The server would have to be updated to download and process the m3u8 file instead of just queueing it as a livestream.

**Comment by Tomoyochan** [comment]
I have submitted a pull for the custom media path.  I am not sure how you would code the direct path and am happy with just the proposed solution you gave for custom media.

**Comment by Tomoyochan** [comment]
If you desire to test it I will be willing to create a custom HLS testing that I would be willing to make public.

**Comment by Tomoyochan** [comment]
Looking at the HLS files I have made the process for adding it without the custom media path would be pulling the first m3u8, getting the url for one of the HLS feeds (Another m3u8).  You would then need to add all the #EXTINF:4.004267, lines.  With the number representing how many seconds that one piece is.   Seems to be quite a bit of work which may not be overly necessary as the custom media path for adding HLS lets you set the actual name of the video which is handy.

**Comment by calzoneman** [comment]
I agree, I don't really want to spend much effort backporting features from custom media manifests to raw file queues since it's intended to be a replacement.

**Comment by calzoneman** [comment]
Closing via https://github.com/calzoneman/sync/commit/8456b6a1251b10d2cb6d5baaccf83ec713e0acae

**Comment by anklimov** [comment]
Gentlemen, what's about sync VoD HLS content?
That's playing well, after upgrading player.js, plenty well managing Subtitles & Audiotrack switch, but still marked as "Livestream" and didn't sync.
How it's possible to allow sync for it?

**Comment by calzoneman** [comment]
Please see the above discussion.  HLS VOD is supported through [custom media manifests](https://github.com/calzoneman/sync/blob/3.0/docs/custom-media.md) only.  If you just try to directly add the m3u8, it will be treated as a livestream because CyTube makes no attempt to parse the m3u8 to determine whether it's prerecorded content or not.
