### ISSUE TITLE
[Question] Renewing the dockerfile

### ISSUE THREAD

**Issue by Gelmo** [calzoneman/sync#774]
Hey Cal,

Have there been any changes to the dockerfile since it was last updated at https://github.com/CyTube/cytube-docker ? If not, please let me know if you intend on renewing this at all. If you don't, just let me know and I'll try to bring it up to date. Are the other new API keys (such as for Mixer, for example) set as ENV vars or are they just called from config files?

Also the FAQ needs to be updated with Mixer and the other new supported site. I'll submit a PR some time this week for it if you don't get around to it first.

Ps: I never heard back from you via email; I assume you got it but if you didn't receive the transfer please let me know. If you did, no need to respond.

**Comment by calzoneman** [comment]
The Dockerfile was originally contributed by user @davidsiaw in
https://github.com/calzoneman/sync/pull/680, where I ended up creating the
separate repository and adding him as a maintainer since I don't really use
Docker.  Looks like it hasn't been updated since the initial proof of
concept.  If you'd like to help maintain the Dockerfile, please let me know.

I don't remember which of the emails from you you're referring to but I
apologize if I forgot to respond, feel free to bump it if it needs a reply.

**Comment by Gelmo** [comment]
Okay, I'll have a go at it and I'll make a PR there once I have something. The email I'm talking about is re: donations, just wanted to make sure you got it

**Comment by calzoneman** [comment]
Moving discussion to https://github.com/CyTube/cytube-docker/issues/1

**Comment by calzoneman** [comment]
>Also the FAQ needs to be updated with Mixer and the other new supported site.

The FAQ is on a GitHub wiki which should be publicly editable without requiring a PR.  However, I've revised it and noted that Mixer is supported.  I'm not sure what you mean by "the other new supported site"; Mixer is the only new site added recently and actually a couple sites mentioned on the FAQ had been deprecated.
