### ISSUE TITLE
Lengthen max chars per message just a bit.

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#782]
Roughly a year ago, Twitter rolled out 280 character tweets.

I've finally gotten around to mucking about my bot to handle that and now CyTube's hard limit of 250 is just shy of what I need. Any opposition to upping this limit to 300 or perhaps 320, so I can send tweet texts and images with embed codes plus a `[Twitter]` header in a single message?

Splitting the message into multiple segments would introduce a problem of trying to determine a suitable split point in a wildly varying input source.

**Comment by calzoneman** [comment]
There are actually 2 limits.

The before-filtering limit is [240](https://github.com/calzoneman/sync/blob/3.0/src/channel/chat.js#L167-L168), which is a more or less arbitrary limit that has existed since the beginning.  There is also a limit of [1000](https://github.com/calzoneman/cytubefilters/blob/master/src/jsfilterlist.cc#L86) after filtering (intentionally longer than the input size limit, to account for filters which add HTML formatting etc.), to prevent people from crashing the service by creating chat filter chains to build up ridiculously long messages.

Here's a comparison of 240 vs 320 in the compact layout: ![2018-11-11-160159_472x399_scrot](https://user-images.githubusercontent.com/385672/48320162-2d8ae800-e5cb-11e8-8e8a-4627b20b19d0.png)

Not opposed to bumping it (in fact, I'd rather bump it than have people split messages, since additional `write()` calls are more expensive than a few extra bytes in one call), however, 320 is starting to get towards the point where I would want to consider adding a permission node for "long messages" to alleviate spam.
