### ISSUE TITLE
Check client clock sync when connections fail

### ISSUE THREAD

**Issue by henke37** [calzoneman/sync#795]
SSL is practically required to run cytube. But SSL hates clients with clocks that are way out of sync and will reject perfectly valid certificates.

As such, in the connection failure message (or the code that shows it), check if the client clock is at least vaguely correct relative to the server.

**Comment by calzoneman** [comment]
Do you have a suggested fix?

As far as I'm aware, the TLS protocol doesn't care about timestamps, but timestamps are used by the client for certificate validation (the server is not involved in this validation beyond providing its certificate).  I checked and one server had a LetsEncrypt certificate renew this morning, so I'm guessing that might be related to why you filed this issue -- if not then I will need an example.  LetsEncrypt sets the "not valid before" field to *an hour prior to the renewal time*, so your clock has to be **really** wrong to encounter this behavior.

Furthermore, cytu.be uses HSTS to force clients to connect over HTTPS, so it's not possible to make an insecure connection to communicate with the server in the case where a certificate is not valid.  Your best bet in this case might be to file a ticket with the appropriate browser vendor to make the error message for invalid certificates more clear in the situation where the issuing date is in the future.  Or you can just fix your clock to not be >1h out of sync.

**Comment by Xaekai** [comment]
This issue was raised regarding the resolution of an issue I helped a user with earlier this morning. The webpage would load, but the socket server wouldn't connect. It seems WebSockets are more finnicky about the clock I guess? Either way the proposed solution is simple: Have the channel page template include it's "birthday" timestamp as a meta element in head, and compare the difference/offset to client. If the difference is significant, the error message can indicate correcting the time on the clients computer as a possible resolution.

![image](https://user-images.githubusercontent.com/594255/52873247-66bf8080-3103-11e9-87bc-09cbbee5bac8.png)

**Comment by Xaekai** [comment]
The issues the user was presenting:

![image](https://user-images.githubusercontent.com/594255/52873642-5956c600-3104-11e9-875e-1984a73ac249.png)

![image](https://user-images.githubusercontent.com/594255/52873650-62479780-3104-11e9-91f1-959f66df81d6.png)

**Comment by calzoneman** [comment]
The website and the backend use different subdomains and therefore
different certificates. It was a backend certificate that updated this
morning and therefore that's why the socket couldn't connect.

If someone wants to take a look at surfacing network errors from socket.io
better I'm open to that, but I'm not keen on adding a datestamp hack for an
extreme edge case. If anything clock skew is the least likely reason for a
connection failure. Far more likely the server is down, or misconfigured,
or the certificate expired, or some firewall blocks that port or protocol.

I find it hard to believe there would be more than a handful of people
worldwide whose system clock would be off by an hour and not notice until
trying to use CyTube at the exact moment the certificate rotated and
therefore get a cert trust error. Most people are using NTP and the certs
only rotate once every few months. I'd be a little more accepting if this
was affecting skew on the order of minutes.

**Comment by calzoneman** [comment]
Closing - no plan to fix
