### ISSUE TITLE
Support for Peertube instances

### ISSUE THREAD

**Issue by freddre** [calzoneman/sync#796]
Hi,

I was wondering if there is a way to integrate peertube into cytube:
https://joinpeertube.org/

There's already a discussion about integrating commands into the API to make it viable.

Here's the link:
https://github.com/Chocobozzz/PeerTube/issues/468

**Comment by calzoneman** [comment]
As it looks like is being discussed in that related issue, a clientside controllable player is one requirement.  The other is a backend data API to allow the server to look up the title, duration, etc.

On the non-technical side, I would like some reasonable evidence that it will be around for a while (previously I've had issues with implementing providers that then went down the next year), and that it will be used enough to warrant the effort to maintain it (for context, the top 5 video providers -- YouTube, Google Drive, self-hosted MP4, Dailymotion, and Twitch -- account for 88.71, 7.31, 2.56, 0.61, 0.32 = 99.51% of all plays in the past 2 weeks, and the bottom 13 video providers combined account for 0.5%).

I plan to write some documentation about the more detailed requirements and process for adding a new video player.  As of right now I don't really do much feature work, but I will be open to reviewing a PR to add this functionality and I can provide some pointers to previous work.

**Comment by fl0werpowers** [comment]
>On the non-technical side, I would like some reasonable evidence that it will be around for a while (previously I've had issues with implementing providers that then went down the next year)

Peertube is not a service, it's a software that allows to host your own tube-like video service. That means it won't go down as long as source code is there (it will be as long as git exists, probably) and if it's supported by someone (currently is by an active French non-profit, Framasoft). That is the key difference, plus that it's peer-to-peer, which in theory should allow seamless video playback that won't make one's server go down in pain.

Edit: to clarify, Peertube might also work as the potential alternative for self-hosted MP4s that might be able to suit the needs of the community.

**Comment by calzoneman** [comment]
These days I'm asking people interested in new video providers to sponsor the development and maintenance themselves by conducting the API research on their own and submitting a pull request to implement the new content.  With that in mind, I do have a concern about PeerTube that needs to be addressed in any PR:

While peer-to-peer avoids the pitfalls of centralization, it also creates a few issues for CyTube:

1. Privacy-conscious users already PM me on a regular basis because they are concerned about whether various features might allow someone else to track their IP address.  Peer-to-peer freaks people out.
2. With a centralized service, if someone uploads a copyrighted work, the service receives a DMCA notice and takes it down.  With peer-to-peer, in certain jurisdictions distributing copyrighted content can result in strike notices etc. against the consumer's internet service account, and punishments are even more severe for outright illegal content (CP etc.).  I don't really want to open people up to the risk of getting their internet shut off just because they joined a channel and someone added an illegitimate PeerTube link.

With this in mind, I think it will be required to have a content warning that the user must accept in order to view.

**Comment by fl0werpowers** [comment]
I've meant that it's peer-to-peer in terms of media playback, not in terms of links themselves. Yes, the potential abuse is there, but if it is a small self-hosted instance, it's nothing more than a self-hosted MP4, amplified with the peer-to-peer capabilities.

The privacy issue is a good question, or at least something i am not as well versed in as i'd like to be in terms of the software part of peertube, and I would personally like to question the devs for. 

However, the key difference between regular server and peertube is that the video is still located on the main server, and the peer-to-peer part is used just to offload traffic from the main server onto those who watch the very content (this means that torrenting occurs on the fact of watching the video and not all the time). The copyright issue is nil because once you take down the server, the content is gone, however the legal part of using torrents as the protocol is a potential risk factor that is worth discussing.

With that I agree with your assessment that this service might potentially require a content warning in order to be used. PeerTube itself has content warnings for things that are NSFW, but those obviously can't be trusted all the time.

Edit: Peertube itself has a warning for P2P usage and asks for consent, so it's not something to worry about either.

**Comment by fl0werpowers** [comment]
There are protocols that are decentralized fully, like the proprietary Ace Stream, which is commonly used to illegally broadcast TV channels or sports livestreams. In that it's basically a torrent file that is user hosted and hardly trackable, unlike PeerTube, which depends solely on the main server, that is the same website one gets and gives the link from. 

The more optimal way to actually do something like peer-to-peer streaming over the web would be just to hook up WebTorrent and wrap it around in custom content somehow, which might take less effort than supporting something more sophisticated and inherently centralized relative to the server like PeerTube.

**Comment by BenLubar** [comment]
As a workaround for Peertube, you can transform an address like https://vid.lubar.me/videos/watch/aafa9e2d-b830-4402-8fcc-eb7cddc1b26c into https://vid.lubar.me/static/webseed/aafa9e2d-b830-4402-8fcc-eb7cddc1b26c-1080.mp4 (assuming there's a 1080p encode of the video)

There's also https://vid.lubar.me/api/v1/videos/aafa9e2d-b830-4402-8fcc-eb7cddc1b26c which can be used to discover these files (as well as HLS playlists when available - https://vid.lubar.me/static/streaming-playlists/hls/aafa9e2d-b830-4402-8fcc-eb7cddc1b26c/master.m3u8 is also this video) and that API can be accessed with CORS from the requesting user's browser if you don't want this accessing arbitrary hostnames

**Comment by Crydsch** [comment]
We too would love this feature to reduce server-load on selfhosted media :D

**Comment by Xaekai** [comment]
Resolved in pending CyTube 3.90-rc release.

**Comment by animeavi** [comment]
> Resolved in pending CyTube 3.90-rc release.

Where could I find this mythical 3.90rc release?

**Comment by Xaekai** [comment]
It was supposed to be out by now, but my mother was diagnosed with cancer, so I've been a bit busy. You can expect the release to be public within the next couple weeks.

**Comment by calzoneman** [comment]
I spent some time last week merging the code and it's out for Xaekai's review.  Once we're good on that, I will push it to the main repo.
