### ISSUE TITLE
Video skipping backwards

### ISSUE THREAD

**Issue by calzoneman** [calzoneman/sync#8]
Check on the server lead function

**Comment by calzoneman** [comment]
Not reproducible

**Comment by Zalg0** [comment]
I noticed that what reproducing this is deleting the video that is right before the video that is currently playing. Even when I select to take leader.

**Comment by calzoneman** [comment]
I actually figured out what this bug was later and patched it.  I was accidentally using a global variable to store the time since the last video update, so when multiple channels were being used it would corrupt the variable and cause the video to sync oddly.

Your issue is distinct; I can reproduce it, but I haven't figured out what (in the code) causes this behavior.

**Comment by Zalg0** [comment]
ah, hm thats kind of weird..Oh well, at the moment it doesn't seem to be that big of an issue I noticed before it would do it for any video deleted now its just the video before the currently playing one. So that's good.

Also, I would like to say I am in full support of this project possibly becoming next synchtube..so far it is really great just like synchtube in the beginning. good work/luck! I do not know very much about code but I will try to help to the best of my ability as a tester/bug reporter.
