### ISSUE TITLE
Invidious Support

### ISSUE THREAD

**Issue by gleb09** [calzoneman/sync#818]
Hello,
I read in a previous issue that you don't do much feature work nowadays but I wanted to ask anyway. Would you consider adding support for Invidious - https://invidio.us/ ? I appreciate cytu.be being a minimal website without Google tracking and I think those that use cytu.be think so too. Invidious is probably the most popular way to watch YouTube for those trying to minimise their exposure to Google services.

Invidious API:
https://github.com/omarroth/invidious/wiki/API

**Comment by calzoneman** [comment]
I generally ask that people submit pull requests for new media providers that meet the requirements.

At a cursory glance, it should be possible, but in this particular case, it may make more sense for someone to develop a userscript to replace CyTube's YouTube player with Invidious instead of adding it as a new provider, since it appears to just be a proxy for YouTube (that way people who want to can also use it for every YouTube video, not just ones explicitly added as Invidious).

However, it does look a little sketchy so I'm not sure I would want to officially support that.  It looks like Invidious is hacking the YouTube data out of the HTML page for the video and presenting it on their own website, which is almost certainly a violation of YouTube's terms of service.
