### ISSUE TITLE
Google Drive Userscript Doesn't Work In Brave Browser

### ISSUE THREAD

**Issue by mikedesu** [calzoneman/sync#837]
I've got Tampermonkey installed. Videos and setup works in Chrome loading videos from Google Drive, but I get the error in Brave:

"The media could not be loaded, either because the server or network failed or because the format is not supported"

Tried x265 and x264 vids, no luck.

**Comment by calzoneman** [comment]
Hi,

Firstly, have you checked whether it is a Brave specific issue?  Google Drive requires 3rd party cookies and sometimes doesn't work for other reasons as well (certain people have said that it doesn't work unless they log in, certain extensions break it, etc.).  You can see some documentation about the 3rd party cookie issue and common extensions which cause problems here: https://github.com/calzoneman/sync/wiki/Google-Drive-Userscript-Installation-Guide#troubleshooting (the instructions talk about Chrome or Firefox, but the principles should be the same for other browsers, just a different options menu).

If there is a problem with the userscript specific to Brave, if someone would like to debug it and provide a patch, feel free to do so, however I'm currently not interested in maintaining the userscript (for any browser).

I generally recommend to avoid Google Drive since it relies on undocumented APIs which have failure modes outside of my control, and which require users to disable privacy protection features in order for it to work.  I would love to delete it; the only reason it still exists in the codebase is because enough people still use it -- if it breaks in a way that would require effort to fix it for existing browsers that work, I would remove the feature instead.

**Comment by mikedesu** [comment]
Genius. Fixed!

That said, if I hosted videos in a place other than Google Drive, it'd
still work fine I imagine, the convenience is just kind of really nice for
my use-case right now...plus I can now use it with Brave! Thank you!

--advertisement removed--
