### ISSUE TITLE
“I have code but there is no data base.”

### ISSUE THREAD

**Issue by antonpictures** [calzoneman/sync#851]
- What triggers the problem?
I opened a brand new amazon AWS account and I gave a guy $30 on fiverr and this link to the code to deploy cytube. 
He sent me this message “Bro i have code but there is no data base.”
What should I tell him?

**Comment by Xaekai** [comment]
That you spent way too much, and should have asked me to set it up for you for $20 instead. Because anyone who either can't read directions or can't find them is not worth $30.

Within the readme on the front page of the web repo:
```md
The official server is located at https://cytu.be, but there are other public
servers hosted for various communities.

## Installation

The installation guide for server administrators is located [on the
wiki](https://github.com/calzoneman/sync/wiki/CyTube-3.0-Installation-Guide).

## Contact
```

Which links to instructions that [explicitly deal](https://github.com/calzoneman/sync/wiki/CyTube-3.0-Installation-Guide#configuration) with this.
