### ISSUE TITLE
IMDb TV content 

### ISSUE THREAD

**Issue by antonpictures** [calzoneman/sync#855]
Can IMDb TV content be added as a  source as well?  https://www.imdb.com/tv/

also tubi.tv?

**Comment by calzoneman** [comment]
I looked at both of these and did not find any embed API that can be used by CyTube.  Correct me if I'm wrong.

Relevant FAQ https://github.com/calzoneman/sync/wiki/Frequently-Asked-Questions#can-you-add-a-new-media-provider

**Comment by antonpictures** [comment]
https://code.tubitv.com. I thought once the video can be viewed publicly on a web page, that video can be streamed anywhere, with the ads and all,  without any embed API nor permissions of some sort.

**Comment by calzoneman** [comment]
CyTube needs some way to hook into the website playing the video to control the synchronization of the time.  This requires the website to vend an API that can be used to do this.  Many websites do not (and some explicitly block embedding into other websites because they don't want their content to appear elsewhere).
