### ISSUE TITLE
Cytube Startup Hangs when Loading Tor Exit List

### ISSUE THREAD

**Issue by mootquex** [calzoneman/sync#879]
Issue solved.

**Comment by yoooby** [comment]
how did you solve it ?

**Comment by calzoneman** [comment]
See the clarification here: https://github.com/calzoneman/sync/wiki/CyTube-3.0-Installation-Guide#running

CyTube doesn't daemonize; it defaults to running in the foreground, so it will print some initialization messages and then continue to wait for connections.

If you would like to detach it into the background, you can use a process manager or init system such as forever or systemd.

**Comment by yoooby** [comment]
oh sorry it's working now, thx

**Comment by yoooby** [comment]
Your browser attempted to submit form data to /register with an invalid authentication token. This may be because:

Your session has expired
Your request was missing the authentication token
A malicious user has attempted to tamper with your session
Your browser does not support cookies, or they are not enabled
If the problem persists, please contact an administrator.
why i got this err ?

**Comment by calzoneman** [comment]
See if https://github.com/calzoneman/sync/issues/730 or https://github.com/calzoneman/sync/issues/505 help you troubleshoot it.
