### ISSUE TITLE
cytubefilters

### ISSUE THREAD

**Issue by Xaekai** [calzoneman/sync#898]
Is there any particular reason this dependency links directly to the github instead of being published on npm under the cytube org like mediaquery? Just curious.

**Comment by calzoneman** [comment]
mediaquery also used to be a git dependency, but I migrated it recently due to an npm 7 issue.  Actually, even that migration needs to be cleaned up, I had to make a new branch to avoid breaking existing clones with the git dependency.

For cytubefilters it's a bit more complicated because it's a C++ wrapper -- which means that the binaries it builds vary by both OS and node version (v8's ABI changes between node major versions).

I think there is a way to ship binaries for different OSes/node versions and fall back to building from source (I believe uWebSockets.js does this), but I haven't invested in figuring that out.

**Comment by calzoneman** [comment]
Resolving because the question was answered.  If desired, packaging cytubefilters can be tracked as an issue in that repository.
