### ISSUE TITLE
Streams' volume control breaking

### ISSUE THREAD

**Issue by ghost** [calzoneman/sync#903]
Debugging steps:

  - Tried clearing the cache & reloading
  - Tried disabling ell extensions+ running browser in Safe Mode.
  - Tried several different streams: some streams w/ no customization *might* fix the problem, but it's not entirely clear to me which streams are "completely" customization-free.
  - Tried different browser: Edge does not exhibit this issue
  

The Problem:

Been noticing this problem in Firefox at https://cytu.be/r/Cinemation over the last couple of months, but this seems to be happening with any stream; I don't remember exactly when I started noticing it. This is observed directly on the website, not any third-party site. 

Messing with stuff outside of the web player seems to have a tendency to break the web player's volume control, resulting in its volume maxing out and desyncing from the video stream. I've had it happen while adjusting volume or screen brightness at the OS level, manipulating the web player's volume control too much, and also while adjusting screen colors using f.lux. Clearing the cache & reloading doesn't work, and neither does disabling all add-ons, or running Firefox in Safe Mode. The only solution I've found so far is to refresh the webpage.

Does not seem to happen in latest version of Edge, for some reason.

### System Information ###

  - Windows 10 64-bit OS Build 19042.868
  - Firefox 64-bit 86.0.1
![Screenshot 2021-03-19 202701](https://user-images.githubusercontent.com/80608205/111853636-38b85600-88f2-11eb-8ea5-8348ebfa5ce4.png)

**Comment by calzoneman** [comment]
Hi,

It shouldn't be possible for the video player itself and external programs to interfere due to browser sandboxing.  It sounds like the issue you're experiencing is likely between the browser and the operating system's audio subsystem, although I've never heard of anyone else experiencing this issue so it could be a problem with your computer specifically.  Your experience with some browsers working and others having this issue could be due to differences in the ways those browsers interact with the audio subsystem.

If you want to troubleshoot it, I'd recommend you try to reproduce the issue (such as by leaving a video running while performing the actions you identified as triggering the problem) and report it to the browser vendor to see if they can advise.

**Comment by ghost** [comment]
It's weird, but I was just messing around with it more, this time getting the glitch to trigger just by zooming in/out on the webpage, and I realized something else.

I don't know yet if it's always like this, but sometimes when the glitch happens, it seems as though the audio stream is actually restarting from the beginning of whatever video stream or embedded video is playing. I would need to watch something with an easily recognizable beginning to confirm this (like a Star Wars movie where if I suddenly started to hear the opening fanfare I could then say "yup, that's the Star Wars theme, the audio is definitely restarting from the beginning.) I need to investigate this more.

In any case, it looks like I'm gonna need to figure out how to reach out to Mozilla next. Thanks for your advice.
