### ISSUE TITLE
No add button

### ISSUE THREAD

**Issue by Graxo** [calzoneman/sync#932]
When i enter a room, there is no add button, the +.
Even when i create a own room there is none. Im the admin with rank 255, how do i fix this? Or what do i need to check?

**Comment by calzoneman** [comment]
The presence of playlist controls is guarded by channel permissions.  If it's being hidden, it's likely that your login is not being recognized (e.g. because the cookie is not being set correctly, or because your socket.io domain is configured differently than the webserver domain).  Revisiting your configuration, and checking the relevant logs and browser network console information would be the right place to begin troubleshooting.

**Comment by calzoneman** [comment]
As an aside, your email host doesn't like my mail server so I can't respond to your email ;)

```
Diagnostic-Code: X-Postfix; connect to filter.spamcheck.eu[195.35.231.161]:25:
    Connection timed out
```

**Comment by Graxo** [comment]
Ahh, then your mailserver is not setup correctly, or your using a relay server that has been blacklisted.
I guess the socket.io domain is not working correctly, but i have up.. ill look at this some other time.

**Comment by calzoneman** [comment]
>Ahh, then your mailserver is not setup correctly, or your using a relay server that has been blacklisted.

I assure you my mailserver works fine and is accepted by gmail, outlook, and other major email providers.  If your mail provider chooses to blacklist a clean IP, that's their problem.

> I guess the socket.io domain is not working correctly, but i have up.. ill look at this some other time.

The web address you provided in the email is just returning 502s.  I'm not sure what you're seeing, because your website does not load at all for me.

**Comment by Graxo** [comment]
I deleted everything. cuz its not working for me now.. so like i said ill look at it some other time.
