### ISSUE TITLE
Permission to hide the viewer list

### ISSUE THREAD

**Issue by mopoIo** [calzoneman/sync#942]
It would be cool to have an option so only mods can see the viewer list

**Comment by calzoneman** [comment]
Why? I don't see the purpose at all.

**Comment by mopoIo** [comment]
So people can join the room and lurk in silence without having to say hi to everyone else

**Comment by calzoneman** [comment]
Then couldn't you just open the channel in an incognito/private browsing
window so that you aren't logged in?

**Comment by mopoIo** [comment]
We have anonymous users blocked and a password to avoid random people
joining

**Comment by calzoneman** [comment]
Your simultaneous desire to join anonymously and also to prevent anonymous
users from joining is quite confusing to me. I don't see the purpose of
this feature.

**Comment by mopoIo** [comment]
In Twitch, when you join a chat, it takes a couple of minutes before your username appears on the viewer list, this gives users room to join and lurk for a couple of minutes and leave. Maybe they join to check what is playing, and if they don't like it they can just leave without it being awkward. We do want people to be anonymous and read our messages but only if it's someone we know. I understand the lack of vision on this topic because as you said on a different feature request, twitch is just a small percentage and it doesn't set the norm.

I managed to show the username on all the messages using javascript, but for the viewer list, users can just disable css and js and gain access again to the viewer list again, that's why I asked.

Sorry for being annoying, I will just go ahead and close this issue.

**Comment by calzoneman** [comment]
I don't necessarily find these issues annoying, I just avoid adding
features that have very niche usage because software maintenance complexity
grows exponentially with the number of features.

One reason that I publish the source code on GitHub with a very permissive
license is that I encourage people who have particular needs to fork it and
customize it to fit the needs of their community. That way, the core
remains relatively small and simple, and different kinds of communities can
add only the features they need on top.
