### ISSUE TITLE
Voteskip passes with 0 eligible voters

### ISSUE THREAD

**Issue by Two-Scoops** [calzoneman/sync#944]
It is possible for a video to get voteskipped when all eligible voters in the room become AFK, even when the voteskippers (most often only one user) themselves are also AFK.
Example:
>[Sun May 08 2022 22:36:22] [playlist] Voteskip passed: 0/0 skipped; eligible voters: 0 = total (59) - AFK (35) - no permission (24); ratio = 0.6

This results in long running videos and streams being skipped when the chat becomes inactive even if a number of people are still watching/listening to it on the side.

**Comment by calzoneman** [comment]
The issue as reported is fixed in https://github.com/calzoneman/sync/commit/fd451fe9d29068b667d360201bd5c75b86dd7d22 (at least, once @Xaekai cherry-picks it to his deployment branch for cytu.be).

In the scenario you described, there is a deeper issue with the definition of "afk" being based on chat message activity in the current code, but that can be addressed as a separate issue.

**Comment by calzoneman** [comment]
Closing since this has been deployed for a while and the discussion about whether the calculation logic for voteskip should change is tracked in #966
