### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by calzoneman** [calzoneman/sync#96]
Don't reload Custom JS when channel settings change if the JS URL didn't change

Add `overflow-x: hidden` to `#messagebuffer`

Check on how GDB's channel got stuck with a negative playlist position

**Comment by coconono** [comment]
you might also want to provide a quick note about not using forever.js with sync. since I kick off sync remotely, I needed something that runs after I log out. 

there seems to be some type of compatibility thing that causes extreme memory usage after about 8 hours. I stopped using that and started using the nohup command(nohup node server.js &) and haven't had any memory freakouts in over 24 hours.

**Comment by calzoneman** [comment]
Which operating system and node version are you using?  There's a bug in newer versions of node on CentOS (and Debian I think) which causes it to use 100% CPU (and in some cases leak memory) when an HTTP response is interrupted.  The issue report is here: https://github.com/joyent/node/issues/5108

For this reason, I downloaded node 0.8.23 and compiled from source on my server, and that version does not have the bug.

I run my server 24/7 and it sticks around 0% CPU and 60MB RAM.
