### ISSUE TITLE
XSS in emote names

### ISSUE THREAD

**Issue by backgroundman** [calzoneman/sync#981]
### Description of the Problem ###

Name an emote `"onload="alert('xss')" ` and send that emote name in chat. Works for any user connected until they reload the page, at which point the emote name isnt converted to the image and therefore not loaded again

**Comment by Xaekai** [comment]
I can not replicate this.

**Comment by calzoneman** [comment]
That's because I hotpatched it before I went to bed

**Comment by backgroundman** [comment]
issue still persists `"onload="alert('xss')"`,  ensure no spaces in emote name
Emote names created with single quotes ' ' cannot be deleted, or renamed

**Comment by calzoneman** [comment]
>issue still persists

Indeed, the "add emote" path was missed in the previous hotfix.  I believe this is more reliably addressed now since I had time to sit down and properly replace the HTML string-building code with DOM construction.

> Emote names created with single quotes ' ' cannot be deleted, or renamed

This is a UI bug, I think.  It actually does get deleted on the server, but the UI loses track of it due to inconsistent escaping of the emote name.  Obviously by the existence of the XSS issue, the emote code was not really carefully written to handle syntax characters.
